export const views_const = {
  inbox: "inbox-view",
  search: "search-view",
  create_outbound: "outbound-create-view",
  create_inbound: "inbound-create-view",
  dashboard: "dashboard-view",
  org_units: "org-unit-view",
  external_entity: "external-view",
  corr_schema: "corr-num-schema-view",
  app_params: "app-param-view",
  picklist: "picklist-view",
  barcode: "barcode-view",
  calendar: "calendar-view",
  user_Prefrence: "user-pref-view",
  outbound_template: "outbound-template-view",
  app_privileges: "app-views-view",
  announcement_groups: "announcements-groups-view",
  stamps: "stamps-view",
  report: "report-view",
  user_delegation: "delegation-view",
  admin_delegation: "delegation-admin-view",
};
