import { ThemeType } from "../../../../types/theme";

const legacy: ThemeType = {
  name: "legacy",
  colors: {
    backgroundText: "#ffffff",
    background: "#f7f7f7",
    backgroundSecondary: "#f0f0f0",
    surface: "#ffffff",
    surfaceHover: "#f5f5f5",
    surfaceActive: "#e8e8e8",
    text: "#000",
    textSecondary: "#4d4d80",
    textMuted: "#6b7280",
    primary: "#264A6B",
    primaryDark: "#13093e",
    primaryLight: "#3b6185af",
    secondary: "#4d4d80",
    accent: "#5385B3",
    border: "#d9d9d9",
    shadow: "rgba(0, 0, 0, 0.15)",
    success: "#4CAF50",
    warning: "#FFC107",
    danger: "#F44336",
    info: "#2196F3",
    disabled: "#9ca3af",
    link: "#5385B3",
    linkHover: "#5385B3",
    overlayColor: "#5385b359",
    overlayTransparency: 6,
    headerBackground: "#5385b39e",
    headerText: "#ffffff",
    footerBackground: "#f0f0f0",
    footerText: "#5385b378",
  },
  typography: {
    fontFamily: '"Roboto", "Arial", sans-serif',
    fontSize: 16,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightBold: 700,
    lineHeight: {
      tight: 1.25,
      normal: 1.5,
      relaxed: 1.75,
    },
    headings: {
      h1: { fontSize: "2.5rem", fontWeight: 700, lineHeight: "1.2" },
      h2: { fontSize: "2rem", fontWeight: 600, lineHeight: "1.3" },
      h3: { fontSize: "1.75rem", fontWeight: 600, lineHeight: "1.4" },
      h4: { fontSize: "1.5rem", fontWeight: 500, lineHeight: "1.4" },
      h5: { fontSize: "1.25rem", fontWeight: 500, lineHeight: "1.5" },
      h6: { fontSize: "1rem", fontWeight: 500, lineHeight: "1.5" },
      body: { fontSize: "1rem", fontWeight: 400, lineHeight: "1.6" },
    },
  },
  spacing: {
    none: "0",
    xs: "12px",
    sm: "12px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "48px",
    xxxl: "64px",
  },
  borderRadius: {
    none: "0",
    small: "4px",
    medium: "8px",
    large: "12px",
    xl: "16px",
    full: "9999px",
  },
  animations: {
    fadeIn: "fade-in 0.3s ease-in-out",
    fadeOut: "fade-out 0.3s ease-in-out",
    slideIn: "slide-in 0.5s ease-in-out",
    slideOut: "slide-out 0.5s ease-in-out",
    scaleIn: "scale-in 0.2s ease-in-out",
    scaleOut: "scale-out 0.2s ease-in-out",
    duration: {
      fast: "150ms",
      normal: "300ms",
      slow: "500ms",
    },
    easing: {
      ease: "ease",
      easeIn: "ease-in",
      easeOut: "ease-out",
      easeInOut: "ease-in-out",
    },
  },
  shadows: {
    none: "none",
    small: "0px 1px 3px rgba(0, 0, 0, 0.12)",
    medium: "0px 3px 6px rgba(0, 0, 0, 0.16)",
    large: "0px 6px 12px rgba(0, 0, 0, 0.2)",
    xl: "0px 12px 24px rgba(0, 0, 0, 0.25)",
    inner: "inset 0px 2px 4px rgba(0, 0, 0, 0.06)",
  },
  breakpoints: {
    xs: "480px",
    sm: "640px",
    md: "768px",
    lg: "1024px",
    xl: "1280px",
    xxl: "1536px",
  },
  zIndex: {
    dropdown: 1000,
    sticky: 1020,
    fixed: 1030,
    modal: 1040,
    popover: 1050,
    tooltip: 1060,
    toast: 1070,
  },
  accessibility: {
    highContrastMode: false,
    reducedMotion: false,
    focusRing: "0 0 0 3px rgba(29, 16, 96, 0.5)",
    focusRingOffset: "2px",
  },
  layout: {
    header: {
      height: "64px",
      background: "#1d1060",
      textColor: "#ffffff",
      alignment: "center",
    },
    footer: {
      background: "#f0f0f0",
      textColor: "#4d4d80",
      alignment: "center",
    },
    sidebar: {
      width: "250px",
      background: "#ffffff",
      textColor: "#1d1060",
    },
    grid: {
      columns: 12,
      gap: "16px",
      maxWidth: "1200px",
    },
  },
  components: {
    button: {
      primary: {
        background: "#1d1060",
        textColor: "#ffffff",
        border: "1px solid #1d1060",
        borderRadius: "8px",
        padding: "12px 24px",
      },
      secondary: {
        background: "transparent",
        textColor: "#1d1060",
        border: "1px solid #1d1060",
        borderRadius: "8px",
        padding: "12px 24px",
      },
      disabled: {
        background: "#9ca3af",
        textColor: "#ffffff",
        border: "1px solid #9ca3af",
        borderRadius: "8px",
        padding: "12px 24px",
      },
    },
    input: {
      background: "#ffffff",
      textColor: "#1d1060",
      border: "1px solid #d9d9d9",
      borderRadius: "8px",
      padding: "12px 16px",
      focusBorder: "1px solid #1d1060",
      placeholderColor: "#6b7280",
    },
    card: {
      background: "#ffffff",
      border: "1px solid #d9d9d9",
      borderRadius: "8px",
      padding: "24px",
      shadow: "0px 3px 6px rgba(0, 0, 0, 0.16)",
    },
  },
};

export default legacy;
