enum LOCALSTORAGE {
    
  LANGUAGE = "LANGUAGE",
  USER = "USER",
  ACL = "ACL",
  THEME = "THEME",
  CUSTOM_THEMES = "CUSTOM_THEMES",
  ACCESS_TOKEN = "ACCESS_TOKEN",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  REFRESH_TOKEN_TIME = "REFRESH_TOKEN_TIME",

  //Legacy
  LEGACY_ACCESS_TOKEN = "LEGACY_ACCESS_TOKEN",
  LEGACY_USER_ID = "LEGACY_USER_ID",

  // Pick list
  PL_CORRESPONDENCE_TYPE = "PL_CORRESPONDENCE_TYPE",
  PL_CORRESPONDENCE_STATUS = "PL_CORRESPONDENCE_STATUS",
  PL_LANGUAGE = "PL_LANGUAGE",
  PL_SECURITY_LEVEL = "PL_SECURITY_LEVEL",
  PL_URGENCY_LEVEL = "PL_URGENCY_LEVEL",
  PL_DOCUMENT_TYPE = "PL_DOCUMENT_TYPE",
  PL_OUTBOUND_TYPE = "PL_OUTBOUND_TYPE",
  PL_PHYSICAL_ATTACHMENT_TYPE = "PL_PHYSICAL_ATTACHMENT_TYPE",
  PL_STAMP_OPTIONS = "PL_STAMP_OPTIONS",
  PL_OUTBOUND_SENDING_TYPE = "PL_OUTBOUND_SENDING_TYPE",
  PL_CORRESPONDENCE_TYPES = "PL_CORRESPONDENCE_TYPES",
  PL_REQUIRED_ACTIONS = "PL_REQUIRED_ACTIONS",
  PL_REJECTION_REASON  = "PL_REJECTION_REASON",
  PL_ROUTE_REQUIRED_ACTIONS = "PL_ROUTE_REQUIRED_ACTIONS",
  PL_APPROVAL_SUBTYPE = "PL_APPROVAL_SUBTYPE",

  // CG PL
  LANGUAGES = "LANGUAGES",
  SECURITY_LEVEL = "SECURITY_LEVEL",
  URGENCY_LEVEL = "URGENCY_LEVEL",
  DOCUMENT_TYPE = "DOCUMENT_TYPE",
  OU_LEVELS = "OU_LEVELS",
  ESCALATION_PERFORMER = "ESCALATION_PERFORMER",
  CORRESPONDENCE_TYPE = "CORRESPONDENCE_TYPE",
  CORRESPONDENCE_STATUS = "CORRESPONDENCE_STATUS",
  OUTBOUND_TYPE = "OUTBOUND_TYPE",
  PHYSICAL_ATTACHMENT_TYPE = "PHYSICAL_ATTACHMENT_TYPE",
  STAMP_OPTIONS = "STAMP_OPTIONS",
  OUTBOUND_SENDING_TYPE = "OUTBOUND_SENDING_TYPE",
  CORRESPONDENCE_TYPES = "CORRESPONDENCE_TYPES",
  REQUIRED_ACTIONS = "REQUIRED_ACTIONS",
  REJECTION_REASON  = "REJECTION_REASON",
  ROUTE_REQUIRED_ACTIONS = "ROUTE_REQUIRED_ACTIONS",
  APPROVAL_SUBTYPE = "APPROVAL_SUBTYPE",

}

export default LOCALSTORAGE