import { AppConstantType } from "./app-constant-type";

export const arabicLabels: AppConstantType = {
  "----------------- Labels -----------------":
    "----------------- Labels -----------------",
  lbl: {
    or: " أو ",
    civil_id: "الرقم المدني",
    creator: "المنشئ",

    assignee: "المُكلَّف",
    add_role: "إضافة صلاحية",
    delegate_all: " تفويض كل الصلاحيات",

    acquired_date: "تاريخ استلام المهمة",
    is_Breach: "مهمة متأخرة ؟",
    total: "العدد الكلي",
    currnet_tasks_st: "أحصاءات المهام الحالية",
    total_Breached: "المهام المتأخرة",
    sla_type: "نوع الأتفاقية",
    sla_time: "التوقيت المحدد",
    postponedToDate: " التأجيل حتي",
    time_start: "وقت البدء",
    end_time: "وقت الإنتهاء",
    postponedEndDate: "تاريخ انهاء التأجيل",
    task_start_date: "تاريخ بدء المهمة",
    current_user: "المستخدم الحالي",
    not_active: "غير مفعل",
    is_delegated_before: "تم التحويل من قبل",
    is_postponed_before: "تم التأجيل من قبل",
    about_version: "الإصدار",
    about_build: "البناء",
    about_release_date: "تاريخ الإصدار",
    about_rights1: "2019 © مجموعة أنظمة الكومبيوتر المتكاملة العالمية (ITS).",
    about_rights2: "جميع الحقوق محفوظة",
    about_visit: "لمزيد من المعلومات، برجاء زيارة",
    active: "مفعل",
    adhoc_user: "المستخدم",
    adminNormalUsers: "حذف العام",
    adminSecretUsers: "حذف الداخلي",
    adminTopSecretUsers: "حذف السري",
    announce_grp: "مجموعة التعميم",
    announce_grp_all_users: "كل المستخدمين",
    announce_grp_code: "معرف مجموعة التعميم",
    announce_grp_email: "البريد الألكترونى لمجموعة التعميم",
    announce_grp_name: "اسم مجموعة التعميم",
    announce_grp_name_ar: "اسم مجموعة التعميم بالعربى",
    announce_grp_name_en: "اسم مجموعة التعميم بالأنجليزى",
    announce_grp_status: "الحالة",
    announce_grp_users: "مستخدمين مجموعة التعميم",
    archived: "الأرشيف",
    approve: "اعتماد",
    approver_title: "المسمى الوظيفى للمعتمد",
    approvers_titles: "قائمة المعتمدين السابقين",
    approveforward: "اعتماد وإرسال",
    approve_action: "مهمة اعتماد الصادر - الإجراء الافتراضي",
    approve_digital_signature: "التوقيع بالتوقيع الرقمى",
    approve_digital_signature_method: "التوقيع الرقمى بواسطة",
    approve_digital_signature_position: "موقع التوقيع الرقمى",
    approve_text: "نص الاعتماد",
    arabic_name: "الاسم باللغة العربية",
    authenticating: "جارى تسجيل الدخول ....",
    average_duration_task: "متوسط مدة المهمة",
    appParam_AdhocEnabled: "تفعيل توجيه الأرشيف",
    appParam_AdhocEnabled_True: "تفعيل",
    appParam_AdhocEnabled_False: "تعطيل",
    appParam_AdhocSendToAll:
      "إختيار مستلم توجيه الأرشيف من قائمة خاصة حسب إعدادات الوحدة التنظيمية للمرسل",
    appParam_AdhocSendToAll_False: "نعم ، سيتم أظهار قائمة خاصة ليختار منها",
    appParam_AdhocSendToAll_True:
      "لا ، سيتم أظهار حقل جميع المستخدمين ليختار منها",
    appParam_ContentSearchEnabled: "تفعيل البحث عن طريق المحتوى",
    appParam_ContentSearchEnabled_True: "نعم",
    appParam_ContentSearchEnabled_False: "لا",
    appParam_onlineEditor: "تفعيل تطبيق تحرير النصوص",
    appParam_digitalSignature: "تفعيل تطبيق التوقيع الرقمى",
    appParam_DigitalSignatureMandatory: "التوقيع الرقمى إلزامى",
    appParam_DigitalSignatureType: "التوقيع الرقمى عن طريق",
    appParam_GeneralStampOnly: "إستخدام الختم العام فى كل مراسلات الصادر",
    appParam_GeneralStampOnly_True:
      "نعم ، سيتم إستخدام الختم العام فى كل مراسلات الصادر",
    appParam_GeneralStampOnly_False:
      "لا ، سوف يقوم المستخدم بالاختيار ما بين الختم العام و ختم الوحدة التنظيمية",
    appParam_InboundOCREnabled:
      "تفعيل التعرف الضوئي على الحروف (OCR) عند إنشاء الوارد",
    appParam_InboundOCREnabled_True:
      "نعم ، سوف يتم إستخراج النص من محتوى المراسلة للمستخدم لكى يستطيع التعديل عليه وحفظه عند إرسال المراسلة",
    appParam_InboundOCREnabled_False:
      "لا ، سوف يتم إرسال المراسلة للاعتماد مباشرة دون إستخراج النص من محتوى المراسلة ولكن المراسلات التى ليس لها نص مستخرج من المحتوى لن تظهر فى نتائج البحث عن طريق المحتوى",
    appParam_MakeTaskActionFromInbox:
      "أتخاذ إجراء(الرد على التوجيه) مهمة نتائج التوجيه من صفحة صندوق المهام",
    appParam_MakeTaskActionFromInbox_True: "نعم",
    appParam_MakeTaskActionFromInbox_False: "لا",
    appParam_OutboundMultipleReceivingEnabled:
      "تفعيل إرسال مراسلة صادر( خارجية أو داخلية) إلى العديد من الجهات فى المرة الواحدة.",
    appParam_OutboundMultipleReceivingEnabled_True: "نعم",
    appParam_OutboundMultipleReceivingEnabled_False: "لا",
    appParam_ShowOutboundCorrespondenceDate:
      "إدخال قيمة تاريخ المراسلة من صفحة إنشاء الصادر",
    appParam_ShowOutboundCorrespondenceDate_True:
      "نعم ، سيتم إظهار حقل تاريخ المراسلة فى صفحة إنشاء الصادر ",
    appParam_ShowOutboundCorrespondenceDate_False:
      "لا ، سيتم إخفاء حقل تاريخ المراسلة فى صفحة إنشاء الصادر وستكون قيمته مساوية لتاريخ الاعتماد النهائى",
    appParam_StampSenderbasedonFinalApproval: "ختم المرسل حسب الاعتماد النهائي",
    appParam_StampSenderbasedonFinalApproval_True:
      "ختم الوحدة التنظيمية صاحبة الموافقة النهائية",
    appParam_StampSenderbasedonFinalApproval_False:
      "ختم الوحدة التنظيمية المنشئة",
    appParam_TwoFactorAuthenticationEnabled:
      "تفعيل المصادقة الثنائية مع تسجيل الدخول للنظام",
    appParam_WebappVersion: "رقم نسخة تطبيق الويب",
    barcode: "الباركود",
    both: "الجميع",
    br_auto_move: "طباعة تلقائية",
    br_current_year: "السنة الحالية",
    br_no: "رقم الباركود",
    br_print_range_from: "رقم الباركود (من)",
    br_print_range_to: "رقم الباركود (إلى)",
    br_print_range_current: "الباركود الحالى",
    br_start_no: "رقم بداية الباركود",
    br_year: "سنة الباركود",
    by: "بواسطة",
    cancel: "الغاء",
    cc_external: "نسخة مطابقة لجهة خارجية",
    cc_internal: "نسخة مطابقة لجهة داخلية",
    cc_list: "قائمة النسخة المطابقة",
    change_urgency: "تغيير الاهمية",
    choose_period: "اختر المدة",
    classification: "التصنيف",
    comment: "التعليق",
    contributorNormalUsers: "تعديل العام",
    contributorSecretUsers: "تعديل الداخلي",
    contributorTopSecretUsers: "تعديل السري",
    consumerNormalUsers: "الاطلاع العام",
    consumerSecretUsers: "الاطلاع الداخلي",
    consumerTopSecretUsers: "الاطلاع السري",
    copy_right:
      "جميع الحقوق محفوظة لشركة الأنظمة المتكاملة العالمية &copy; 2018 ",
    copy_right17: "جميع الحقوق محفوظة &copy; 2018",
    correspondence: "المراسة",
    corr_date: "تاريخ المراسلة",
    corres_date_from: "تاريخ المراسلة من",
    corres_date_to: "تاريخ المراسلة الي",
    corr_details: "بيانات المراسلة",
    corr_number: "رقم المراسلة",
    corr_status: "حالة المراسلة",
    corr_subject: "موضوع المراسلة",
    corr_types: "نوع المراسلة",
    correspondence_type: "نوع المراسلة",
    created_by_me: "تم الإنشاء بواسطتي",
    create_out_action:
      "شاشة إنشاء المراسلة الصادرة - القيمة الافتراضية لنوع الختم",
    create_out_def_template:
      "شاشة إنشاء المراسلة الصادرة - القيمة الافتراضية لنموذج المراسلة الصادرة",
    create_out_doc_default:
      "شاشة إنشاء المراسلة الصادرة - القيمة الافتراضية لنوع المستند",
    creation_date: "تاريخ الإنشاء",
    creation_date_from: "تاريخ الإنشاء من",
    creation_date_to: "تاريخ الإنشاء إلي",
    default: "افتراضى",
    date_from: "التاريخ (من)",
    date_to: "التاريخ (إلى)",
    deleted: "محذوف",
    delete_all: "مسح الكل",
    delete_selected: "مسح المحدد",
    description: "الوصف",
    document_type: "نوع المستند",
    duration: "المدة",
    email: "البريد الإلكتروني",
    end_task_date: "تاريخ انتهاء المهمة",
    english_name: "الاسم باللغة الإنجليزية",
    enter_comment: "التعليق",
    error_type: "نوع الخطأ",
    escalation: "رسائل تصعيد",
    escalation_performer: "منفذ التصعيد",
    expected_reply_date: "تاريخ الرد المتوقع",
    external: "خارجي",
    external_entity: "الجهة الخارجية",
    ext_ent_classification: "تصنيف الجهة الخارجية",
    ext_ent_name: "اسم الجهة الخارجية",
    false: "لا",
    fax_number: "رقم الفاكس",
    ext_ref_num: "الرقم المرجعي الخارجي",
    file_content: "محتوى الملف",
    file_name: "اسم الملف",
    final_approv_org_unit: "الوحدة التنظيمية للموافقة النهائية",
    final_approve_ext_out:
      "التحكم في امكانية الاعتماد النهائي للمراسلات الصادرة لجهات خارجية معينة",
    final_approve_int_out:
      "التحكم في امكانية الاعتماد النهائي للمراسلات الصادرة لوحدات تنظيمية معينة",
    finish: "أنهاء",
    forwardToOrgunit: "قائمة الارسال للاعتماد",
    from_local_file: "من الحاسب الشخصي",
    from_template: "من نموذج جاهز",
    general: "عام",
    not_general: "وحدة تنظيمية",
    g2g_group: "مجموعة الاستقبال (G2G)",
    gen_announce_schema:
      "إنشاء رقم المراسلة استنادا إلى مقطع رقم المراسلة - التعاميم",
    gen_corr_num_acquis_info1:
      "إنشاء رقم المراسلة الواردة عند قبول الوحدة التنظيمية",
    gen_corr_num_acquis_info2:
      "إنشاء رقم المراسلة الواردة عند إنشائها من وحدة الأرشيف",
    gen_corr_num_schema_info1:
      "إعادة ضبط الرقم التسلسلي للمراسلة مع كل تغيير في بنود مقطع رقم المراسلة",
    gen_corr_num_schema_info2: "إعادة ضبط الرقم التسلسلي للمراسلة كل عام",
    gen_inbound_schema:
      "إنشاء رقم المراسلة استنادا إلى مقطع رقم المراسلة - المراسلات الواردة",
    gen_internal_schema:
      "إنشاء رقم المراسلة استنادا إلى مقطع رقم المراسلة - المراسلات الداخلية",
    gen_out_approv_info1:
      "إنشاء رقم المراسلة الصادرة بعد الاعتماد النهائي للمراسلة",
    gen_out_approv_info2: "إنشاء رقم المراسلة الصادرة بمجرد إنشاء المراسلة",
    gen_out_send_bas_info1:
      "يقصد بها أن المرسل هو مرسل الوحدة التنظيمية المنشئة للمراسلة الصادرة ",
    gen_out_send_bas_info2:
      "يقصد بها أن المرسل هو مرسل الوحدة التنظيمية للمعتمد النهائي للمراسلة الصادرة",
    gen_outbound_schema:
      "إنشاء رقم المراسلة استنادا إلى مقطع رقم المراسلة - المراسلات الصادرة",
    grant_access_parent: "اعطاء الصلاحية للوحدة التنظيمية الاعلي",
    inboundRoutingNormalUsers: "موجهين العام",
    inboundRoutingSecretUsers: "موجهين الداخلي",
    inboundRoutingTopSecretUsers: "موجهين السري",
    inboundRoutingNormalOrgunit: "موجهين العام للوحدة التنظيمية",
    inboundRoutingSecretOrgunit: "موجهين الداخلي للوحدة التنظيمية",
    inboundRoutingTopSecretOrgunit: "موجهين السري للوحدة التنظيمية",
    inboundCCNormalUsers: "النسخة المطابقة للعام",
    inboundCCSecretUsers: "النسخة المطابقة للداخلي",
    inboundCCTopSecretUsers: "النسخة المطابقة للسري",
    inboundCCNormalOrgunit: "النسخة المطابقة للوحدة التنظيمية العام",
    inboundCCSecretOrgunit: "النسخة المطابقة للوحدة التنظيمية للداخلي",
    inboundCCTopSecretOrgunit: "النسخة المطابقة للوحدة التنظيمية للسري",
    inb_search_type_action: "بحث الوارد - القيمة الافتراضية نوع الوارد",
    inbound_sender_name: "مرسل الوارد",
    inbound_cc_email_option: "البريد الإلكتروني للنسخة المطابقة للوارد",
    inbound_receive_final_route: "استلام التوجية الاخير",
    inbound_routing_user: "استلام التوجية",
    index_user: "المستخدم الذي قام بالأرشفة",
    initiation_org_unit: "الوحدة التنظيمية المنشئة",
    initiatorUsers: "منشئين الصادر",
    internal_entity: "الجهة الداخلية",
    internal: "داخلي",
    is_general: "عام ؟",
    is_active: "مفعلة",
    is_deactivatable: "قابلة لالغاء التفعيل",
    issuer_entity: "الجهة المنشئة",
    KB: "ك.ب.",
    keywords: "الكلمات المفتاحية",
    no_data: "لا توجد بيانات",
    language: "اللغة",
    loading: "جارى التحميل",
    move_up: "التحريك لأعلي",
    move_down: "التحريك لأسفل",
    name: "الاسم",
    no: "لا",
    notactive: "معطل",
    notifications: "الإشعارات",
    notify_cleaner_days: "أقصى مدة للأبقاء على الاشعارات قبل الحذف (الأيام)",
    notify_receive_route: "اشعار استلام التوجية",
    notify_outbound_receive_final: "اشعار استلام الوارد الاخير",
    need_reply: "بحاجة إلى رد",
    new_inbound_action: "مراسلة واردة جديدة - الإجراء الافتراضي",
    number_completed_tasks: "عدد المهام المكتملة",
    number: "الرقم",
    ocr_text: "نص محتوى المراسلة",
    org_unit: "الوحدة التنظيمية",
    org_unit_approver_next: "الوحدة التنظيمية التالية المعتمدة",
    org_unit_code: "كود الوحدة التنظيمية",
    org_unit_email: "البريد الإلكتروني للوحدة التنظيمية",
    org_unit_level: "مستوي الوحدة التنظيمية",
    org_unit_manager: "مدير الوحدة التنظيمية",
    org_unit_name: "اسم الوحدة التنظيمية",
    org_unit_parent: "الوحدة التنظيمية الاعلي",
    org_stamp: "ختم المؤسسة",
    org_unit_stamp: "ختم الجهة المنشئة",
    org_units: "الوحدات التنظيمية",
    orgunit_canSendOutboundAnnouncements:
      "المجموعات التى يمكن للوحدة إرسال تعميم لها",
    orgunit_canSendOutboundAnnouncements_flag: "إرسال التعاميم",
    orgunit_canSendOutboundDecisions:
      "المجموعات التى يمكن للوحدة إرسال قرار لها",
    orgunit_canSendOutboundDecisions_flag: "إرسال القرارات",
    outboundApprovalNormalUsers: "مستخدموا إعتماد الصادر العام",
    outboundApprovalSecretUsers: "مستخدموا إعتماد الصادر الداخلي",
    outboundApprovalTopSecretUsers: "مستخدموا إعتماد الصادر السري",
    outboundReviewerNormalUsers: "مستخدموا مراجعة الصادر العام",
    outboundReviewerSecretUsers: "مستخدموا مراجعة الصادر الداخلي",
    outboundReviewerTopSecretUsers: "مستخدموا مراجعة الصادر السري",
    outboundSenderNormalUsers: "مستخدموا مرسلين الصادر العام",
    outboundSenderSecretUsers: "مستخدموا مرسلين الصادر الداخلي",
    outboundSenderTopSecretUsers: "مستخدموا مرسلين الصادر السري",
    outbound_type: "نوع الصادر",
    out_final_approver: "المعتمد النهائي للصادر",
    out_reply_ref_number: "الرقم المرجعي للرد الخاص بالصادر",
    over_due: "متأخر التنفيذ",
    per_day: "يوم",
    per_taskname: "حسب اسم المهمة",
    per_workflow: "حسب نوع مسار العمل",
    permited_org_unit_sent_to: "الوحدات التنظيمية المسموح الارسال لها",
    permited_ext_entity_sent_to: "الوحدات الخارجية المسموح الارسال لها",
    phone: "الهاتف",
    previous_comment: "تعليق المستخدم السابق",
    param_grant_read_inbound_issuer: "إعطاء مجموعة منشئ الوارد صلاحية القراءة",
    param_inbound_fyi_route_option: "طريقة إرسال توجيه (FYI) لمراسلة الوارد",
    picklist_ar_label: "الاسم العربي لعنصر القائمة",
    picklist_en_label: "الاسم الاجنبي لعنصر القائمة",
    picklist_type: "نوع القائمة",
    picklist_category: "فئة القوائم",
    picklist_item: "عنصر القائمة",
    profile_name_ar: "الاسم العربي للمجموعة",
    profile_name_en: "الاسم الأجنبي للمجموعة",
    profile_code: "كود المجموعة",
    profile_views: "صلاحيات المجموعة",
    profile_users: "مستخدمين المجموعة",
    quantity: "الكمية",
    reac_inbou_action: "الاستجابة لمراسلة واردة - الإجراء الافتراضي",
    reac_rej_inb_action: "الاستجابة لمراسلة واردة مرفوضة - الإجراء الافتراضي",
    receive_acknowledge: "إشعار بالوصول",
    receive_date_from: "تاريخ الاستلام من",
    receive_date_to: "تاريخ الاستلام إلي",
    reciever_type: "نوع مستلم المراسلة",
    receiving_entity: "الجهة المستلمة",
    recvinbNormalUsers: "مستلموا العام",
    recvinbSecretUsers: "مستلموا الداخلي",
    recvinbTopSecretUsers: "مستلموا السري",
    redirectting: "جارى التوجيه ....",
    reject: "رفض",
    rejection_comment: "تعليق الرفض",
    rejection_reason: "سبب الرفض",
    related_ref_num: "مراسلات ذات صلة",
    remarks: "ملاحظات",
    reminder: "رسائل تذكير",
    reply_comment: "تعليق الرد",
    reply_date: "تاريخ الرد",
    report_name: "اسم التقرير",
    reqired_action: "الإجراء المطلوب",
    resend: "إعادة إرسال",
    review_correspondence: "مراجعة المراسلة",
    route: "توجية",
    route_comment: "تعليق التوجيه",
    route_date: "تاريخ التوجيه",
    route_date_from: "تاريخ التوجيه (من)",
    route_date_to: "تاريخ التوجيه (إلى)",
    route_from: "التوجيه من",
    route_from_org: "التوجيه من (وحدة تنظيمية)",
    route_from_user: "التوجيه من (مستخدم)",
    route_status: "حالة التوجيه",
    route_sender_org: "مرسل التوجيه (وحدة تنظيمية)",
    route_sender_user: "مرسل التوجيه (مستخدم)",
    route_receiver_org: "مستلم التوجيه (وحدة تنظيمية)",
    route_receiver_user: "مستلم التوجيه (مستخدم)",
    route_to: "التوجيه إلى",
    route_type: "نوع التوجيه",
    scan_user: "المستخدم الذي قام بالمسح الضوئي",
    search_contentSearch: "البحث بالمحتوى",
    search_isDeleted: "محذوف",
    search_createdByMe: "تم الإنشاء بواسطتي",
    security_level: "مستوى السرية",
    select_approver: "الجهة المعتمدة التالية",
    select_approver_user: "اسم المعتمد التالي",
    select_reviewer_user: "اسم المراجع",
    select_approval_user: "اسم الموافق",
    select_issuers_users: "مجموعة المنشئين",
    select_reviewer_users: "مجموعة المراجعين",
    select_approval_users: "مجموعة المعتمدون",
    send_any_internal: "التحكم في امكانية الارسال لوحدة تنظيمية داخلية معينة",
    send_email_fyi_routing: "إرسال التوجيه (FYI) عن طريق بريد إلكترونى",
    send_email_to_cc: "ارسال بريد التكروني لقائمة النسخة المطابقة",
    send_task_fyi_routing: "إرسال التوجيه (FYI) كمهمة",
    send_task_to_cc: "ارسال مهمة لقائمة النسخة المطابقة",
    send_date: "تاريخ الإرسال",
    send_date_from: "تاريخ الإرسال من",
    send_date_to: "تاريخ الإرسال الي",
    sender_id: "كود المرسل",
    sender_name: "اسم المرسل",
    sender_phone: "هاتف المرسل",
    sender_type: "نوع مرسل المراسلة",
    sending_method: "طريقة الإرسال",
    sending_entity: "الجهة المرسلة",
    task_sending_entity: "الجهة المرسلة للمهمة",
    last_comment: "تعليق المستخدم السابق",
    sequence_number: "الرقم المسلسل",
    scanIndexUsers: "مستخدمين المسح الضوئي",
    short_number: "الرقم المختصر",
    show_orgunit: "أضغط هنا لعرض الوحدات التنظيمية",
    show_more: "عرض الكل",
    show_less: "عرض أقل",
    since: "منذ",
    sign_date: "تاريخ الموافقة",
    sign_date_from: "تاريخ الموافقة من",
    sign_date_to: "تاريخ الموافقة الي",
    size: "الحجم",
    stamp_general: "الختم العام",
    stamp_review: "ختم المراجعة",
    stamp_g2g: "ختم G2G",
    stamp_type: "نوع الختم",
    stamp_of: "ختم",
    start: "البداية",
    start_task_date: "تاريخ بدء المهمة",
    status: "الحالة",
    subject: "الموضوع",
    task_analysis: "تحليل المهام",
    task_name: "اسم المهمة",
    task_sent_date: "تاريخ الإرسال",
    tasks_completed: "عدد المهام المكتملة",
    task_due_date: "تاريخ نفاذ وقت المهمة",
    template: "نموذج",
    template_name: "اسم القالب",
    template_file_name: "اسم ملف القالب",
    template_orgunit: "الوحدات التنظيمية للقالب",
    time_unit: "وحدة زمنية",
    to_user: "إلي مستخدم",
    total_num_tasks: "المهام الكلية",
    true: "نعم",
    type: "النوع",
    type_of_schema: "نوع المخطط",
    type_of_segment: "نوع المقطع",
    urgency_level: "مستوى الأهمية",
    user: "المستخدم",
    user_en_name: "اسم المستخدم الاجنبي",
    user_ar_name: "اسم المستخدم العربي",
    user_civil_id: "رقم الهوية",
    user_two_factor_auth: "تفعيل المصادقة الثنائية مع تسجيل الدخول للنظام",
    user_title: "المسمي الوظيفي",
    user_title_en_name: "المسمي الوظيفي بالاجنبي",
    user_title_ar_name: "المسمي الوظيفي بالعربي",
    user_title_default: "افتراضى",
    user_title_order: "الترتيب",
    user_title_set: "بالمراسلة",
    user_login_name: "اسم تسجيل دخول المستخدم",
    user_orgunit: "الوحدة التنظيمية للمستخدم",
    user_name: "اسم المستخدم",
    user_pass: "كلمة السر",
    warning: "تنبيه",
    welcome: "مرحبا  ",
    yes: "نعم",
    org_unit_opentextInboundExternalFolderId:
      "كود مجلد الربط مع نظام الأرشيف للمراسلات الواردة الخارجية",
    org_unit_opentextInboundInternalFolderId:
      "كود مجلد الربط مع نظام الأرشيف للمراسلات الواردة الداخلية",
    org_unit_opentextOutboundExternalFolderId:
      "كود مجلد الربط مع نظام الأرشيف للمراسلات الصادرة الخارجية",
    org_unit_opentextOutboundInternalFolderId:
      "كود مجلد الربط مع نظام الأرشيف للمراسلات الصادرة الداخلية",
    org_unit_opentext: "نظام الأرشيف للمراسلات",
    urgency_notification: "مستوى الأهمية",
    period_unit: "الفترة الزمنية قبل كل تنبيه",
    duration_unit: "وحدة زمن الفترة",
    escalation_after_how_many_reminders: "عدد مرات ارسال التنبيه قبل التصعيد",
    corres_duration: "المدة الزمنية لأنهاء المراسلة",
    hour: "ساعة",
    day: "يوم",
    minute: "دقيقة",
    second: "ثانية",
    millisecond: "ملى ثانية",
    FYA: "للإجراء",
    FYI: "للعلم",
    g2gCode: "كود الجهة الحكومية (G2G)",
    g2gBranch: "كود فرع الجهة الحكومية (G2G)",
    enableG2G: "تفعيل (G2G)",
    receiving_branch: "الفرع المرسل",
    size_file: "أقصى حجم ملف المرفق (MB)",
    copy: "نسخ الى ",
    show_general: "عرض العام ",
    users: "المستخدمين",
    read_receipt: "إعلام القراءة",
    sender_name_to: " اسم المرسل إليه",
    delegation_from: "تفويض من",
    delegation_to: "تفويض إلى",
    delegation_date_from: "التاريخ من",
    delegation_date_to: "التاريخ إلى",
    delegation_craeted_on: "تاريخ الإنشاء",
    delegation_status: "الحالة",
    delegations: "التفويضات",
    delegation_days: "عدد الأيام",
    content: "المحتوى",
    my_delegation: "المفوضين لى",
    delegation_history: "سجل إجراءات التفويض",
    cc_user: "نسخة مطابقة للمستخدمين ",
    delegate: "التفويضات : ",
    actiontype: "الإجراء",
    domaintype: "النوع",
    actiondate: "تاريخ الإجراء",
    viewActions: "عرض الإجراءت",
    SkipPdfConverter: "تخطى تحويل pdf",
    orgUnitAbbreviation: "مختصر الوحدة التنظمية",
    display_alluser: "عرض جميع المستخدمين فى النظام",
    display_orgunit: "إتبع قواعد الوحدة التنظيمية",
    user_pref_home_page: "الصفحة الرئيسية المفضلة",
    user_pref_inbox_view: "صفحة صندوق المهام المفضلة",
    user_pref_receiving_notifications: "الأشعارات التى تريد أستقبالها",
    user_pref_receiving_emails: "رسائل البريد الإلكترونى التى تريد أستقبالها",
    user_pref_user_image: "صورة الملف الشخصى",
    user_pref_user_signautre: "التوقيع",
    AllowedOrgUnit: "الوحدات التنظيمية المسموح بها",
    approve_orgunit: "الوحده التنظيمية لمجموعة المعتمدين",
  },

  "----------------- Buttons -----------------":
    "----------------- Buttons -----------------",
  btn: {
    login_with_hawyti: "تسجيل الدخول بواسطة هويتى",
    about: "عن المرسال",
    acquire: "قبول",
    activate: "تفعيل",
    add_new: "إنشاء جديد",
    add_segment: "إضافة مقطع",
    adhoc_create: "إنشاء توجيه أرشيف",
    advanced_search: "بحث متقدم",
    announce_grp_assign_users: "تعيين مستخدمين",
    attachment_edit: "تعديل بيانات المرفق",
    auto_clearSelection: "حذف المختار",
    auto_search: "البحث",
    auto_selectAll: "إختيار الكل",
    auto_showLess: "عرض أقل",
    auto_showMore: "عرض الكل",
    back: "السابق",
    browse: "تحميل",
    cancel: "إلغاء",
    change_profile_image: "تغيير صورة الملف الشخصي",
    change_signature_image: "تغيير صورة التوقيع",
    create_continue: "انشاء & متابعة",
    create_new: "انشاء & جديد",
    create_inbound: "انشاء وارد",
    create_outbound: "انشاء صادر",
    clear: "تفريغ",
    clear_options: "تفريغ الحقول",
    close: "إغلاق",
    back_page: " الصفحة السابقة",
    complete: "أنهاء",
    complete_task_read: "أنهاء المهمة وإعلام قراءة",
    complete_task: "أنهاء المهمة",
    complete_tasks: "أنهاء المهام",
    continue: "أستكمل",
    create: "إنشاء",
    create_all: "إنشاء متعدد",
    create_schema: "إنشاء المقطع",
    change_file: "تغيير الملف",
    custom_duration: "فترة معينة",
    deactivate: "تعطيل",
    default: "اجعله افتراضى",
    delete: "حذف",
    delete_all: "حذف الكل",
    delete_draft: "حذف النسخة المؤقتة",
    delete_schema: "حذف المقطع",
    delete_segment: "حذف المقطع",
    delivery_note_create: "إضافة توقيع بالاستلام",
    delivery_note_delete: "حذف توقيع الاستلام",
    delivery_note_delete_create: "حذف وإضافة توقيع الاستلام جديد",
    download: "تنزيل",
    downloadAll: "تنزيل الكل",
    download_pdf: "تنزيل بصيغة PDF",
    download_tiff: "تنزيل بصيغة TIFF",
    download_template: "تنزيل القالب",
    edit: "تعديل",
    edit_segment: "تعديل المقطع",
    finish: "أنهاء",
    filter: "معايير البحث",
    generate_barcode: "إصدار الباركود",
    group: "تجميع",
    hidden: "إخفاء",
    import: "استيراد ملف",
    import_new_version: "استيراد نسخة جديدة",
    inbound_save_ocr: "حفظ النص",
    corres_download_latest: "تنزيل أخر نسخة للمراسلة",
    login: "تسجيل الدخول",
    login_windows_auth: "تسجيل الدخول من خلال ويندوز",
    logout: "تسجيل الخروج",
    manual_admin: "دليل مسئول النظام",
    manual_user: "دليل المستخدم",
    move: "تحريك",
    move_up: "تحريك لأعلى",
    move_down: "تحريك لأسفل",
    new_inbound: "وارد جديد",
    new_outbound: "صادر جديد",
    next: "التالي",
    no: "لا",
    ok: "موافق",
    previous: "السابق",
    print_barcode: "طباعة الباركود",
    refresh: "تحديث",
    report_view: "عرض التقرير",
    report_print: "طباعة التقرير",
    reset: "إعادة الوضع الأصلي",
    reset_barcode: "إعادة تعيين",
    resubmit: "إعادة إرسال",
    route_add: "أضافة التوجيه",
    route_edit: "تعديل التوجيه",
    route_send: "إرسال التوجيه",
    route_terminate: "إيقاف التوجيه",
    save: " حفظ",
    save_changes: "حفظ التغييرات",
    save_draft: "حفظ نسخة مؤقتة",
    save_schema: "حفظ المقطع",
    scan: "المسح الضوئي",
    search: "بحث",
    seeAll: "عرض الكل",
    select: "اختيار",
    select_action: "الإجراء",
    select_file: "اختيار الملف",
    sendG2G: "إرسال (G2G)",
    setting: "الإعدادات",
    showmore: "إظهار المزيد",
    start_print: "إبدا الطباعة",
    stop: "إيقاف",
    submit: "إرسال",
    switch_inbox_list: "تحويل الى شكل القائمة",
    switch_inbox_table: "تحويل الى شكل الجدول",
    task_actions: "الإجراء",
    task_other_actions: "إجراء أخر",
    task_complete_edit: "تعديل بيانات إنهاء المهمة",
    task_remove: "حذف المهمة من قائمة الإنهاء",
    task_sendDelayComment: "إرسال تعليق تأخير المهمة",
    tasks_complete_multi: "إنهاء مهام",
    tasks_complete_multi_reply_routing: "الرد على التوجيهات",
    tasks_complete_multi_routings_replies: "الرد بنتائج التوجيهات",
    tasks_complete_multi_finish_inbound: "نتائج التوجيهات وانهاء الوارد",
    title_change_order: "تغيير الترتيب",
    title_delete_corres: "حذف من المراسلة",
    title_reorder: "اعادة ترتيب",
    title_set_corres: "أضافة للمراسلة",
    title_swap_order: "تبادل الترتيب",
    today: "اليوم",
    upload: "تحميل",
    upload_out_corres_doc: "تحميل وثيقة مراسلة الصادر",
    upload_files: "تحميل الملفات",
    upload_template: "تحميل القالب",
    userPreference_addToOrgunit: "إضافة إلى الوحدة التنظيمية",
    view: "عرض",
    yes: "نعم",
    assignUsersToProfile: "تعيين المستخدمين للمجموعة",
    show_views: "إضغط هنا لعرض صلاحيات المجموعة",
    show_users: "إضغط هنا لعرض مستخدمين المجموعة",
    assign: "تعيين",
    notread: "إعتبارها غير مقروءة",
    read: "إعتبارها مقروءة",
    sync: "مزامنة المستخدمين",
    quickly_add_user: " إضافة سريعة للمستخدمين",
    select_all: "إختيار الكل",
    replay_to: "الرد على المراسلة",
    uploadNewVersion: "تحميل نسخة جديدة",
    viewHistory: "سجل الأحداث",
    create_close: "انشاء & وإغلاق",
    print_task_corr: "طباعة المراسلة",
    downolad_templete: "تحميل النموذج",
    user_preferences: "إعدادات المستخدم",
    view_all: "عرض الكل",
    view_changes: "عرض التعديل فقط",
    loginwith: "تسجيل الدخول بهذا المستخدم",
    send_user: "إرسال الى مستخدم",
    quickly_add_orgunit: "إضافة سريعه للوحدات التنظيمية",
    delete_user: "حذف المستخدم",
    add_user: "إضافه مستخدم",
    permission: "",
    SkipPdfConverter: "",
  },

  "----------------- Titles -----------------":
    "----------------- Titles -----------------",
  til: {
    performance: "الأداء",
    about: "عن المرسال",
    add_attachment: "المرفقات",
    add_cc: "إضافة نسخة مطابقة",
    adhoc: "توجيه أرشيف",
    adhoc_create: "إنشاء توجيه أرشيف",
    admin_group: "مجموعة الحذف",
    advancedSearchCirteria: "معايير البحث المتقدم",
    all: "الكل",
    announcement: "تعميم",
    announce_grp: "مجموعة التعميم",
    announce_grp_assign_users: "تعيين مستخدمين فى مجموعة التعميم",
    announce_grp_search: "البحث عن مجموعة تعميم",
    app_notifications: "إشعارات التطبيق",
    attachments: "مرفقات",
    attachmentHistory: "تاريخ المرفق",
    attachment_create_multi_electronic: "إنشاء مرفقات الالكترونية",
    attachment_uploading_list: "قائمة التحميل",
    basic_info: "بيانات المراسلة",
    basicSearchCirteria: "معايير البحث الأساسية",
    cc_orgunit: "النسخة المطابقة للوحدة التنظيمية",
    cc_user: "النسخة المطابقة للمستخدمين",
    contributor_group: "مجموعة التعديل",
    consumer_group: "مجموعة الاطلاع",
    corr_filter: "بحث المراسلات",
    corr_out_created_me: "مراسلات صادرة قمت بإنشائها",
    corr_out_reviewed_me: "مراسلات صادرة قمت بمراجعتها",
    corr_out_approved_me: "مراسلات صادرة قمت باعتمادها",
    corr_in_created_me: "مراسلات واردة قمت بإنشائها",
    corr_in_routed_me: "مراسلات واردة قمت بتوجيهها",
    corr_in_routed_cc_me: "مراسلات واردة تم توجيهها إلي كنسخة مطابقة",
    corr_in_route_replied_me: "مراسلات واردة قمت بالرد على التوجيه",
    corr_in_completed_me: "مراسلات واردة قمت بإنهائها",
    corr_related: "مراسلات ذات صلة",
    delete_access_group: "مجموعة المسح",
    default_actions: "القيم الافتراضية",
    details: "بيانات إضافية",
    edit: "تعديل",
    edit_access_group: "مجموعة التعديل",
    electronic_attachment: "المرفقات الالكترونية",
    external_inbound: "وارد خارجي",
    external_outbound: "صادر خارجي",
    ext_ent_search_criteria: "معايير بحث الجهات الخارجية",
    fill_form: "بيانات المراسلة",
    filtertabs_all: "الكل",
    followup: "المتابعة",
    gen_corr_num_acquisition: " إنشاء رقم المراسلة الواردة بعد قبول المهمة",
    gen_corr_num_schema: " إنشاء رقم المراسلة استنادا إلى المقطع",
    gen_out_approval:
      "إنشاء رقم المراسلة الصادرة الخارجية/الداخلية بعد الاعتماد ",
    gen_out_send_bas_approv:
      "مرسل المراسلة الصادرة حسب الوحدة التنظيمية للمعتمد النهائي",
    history: "سجل الإجراءات",
    import_ext_ent_template: "استيراد الجهات الخارجية",
    inbound: "الوارد",
    inbound_edit_ocr_text: "تعديل نص محتوى المراسلة",
    inbound_form: "شاشة الوارد",
    inbound_resubmit: "إعادة إرسال الوارد",
    inbound_recipient_group: "مجموعة مستلموا الوارد",
    internal: "داخلي",
    kpi: "معدل أدائى",
    login: "تسجيل الدخول",
    notification: "الاشعارات",
    medium_criteria: "المعايير المتوسطة",
    more_info: "بيانات إضافية",
    org_unit: "الوحدات التنظيمية",
    org_unit_code: "كود الوحدة التنظيمية",
    org_unit_data: "بيانات الوحدة التنظيمية",
    org_unit_email: "البريد الإلكتروني ",
    org_unit_in_roles: "ادوار مستخدمين الوارد",
    org_unit_name_ar: "الاسم  باللغة العربية",
    org_unit_name_en: "اسم  باللغة الإنجليزية",
    org_unit_out_roles: "ادوار مستخدمين الصادر",
    org_unit_search_criteria: "معايير بحث الوحدة التنظيمية",
    org_unit_users: "مستخدمين الوحدة التنظيمية",
    orgunit_outbound_announcements_decisions: "التعاميم و القرارات",
    outbound: "الصادر",
    outbound_file: "ملف الصادر",
    outbound_templates: "قوالب الصادر",
    outbound_form: "شاشة الصادر",
    outbound_initiator_group: "مجموعة منشئين الصادر",
    outbound_reviewer_group: "مجموعة مراجعين الصادر",
    outbound_restrict_recipient: "التحكم في امكانية الارسال للوحدة التنظيمية",
    outbound_restrict_final_approval: "التحكم في الاعتماد النهائي",
    outbound_approval_group: "مجموعة معتمدين الصادر",
    outbound_sender_group: "مجموعة مرسلين الصادر",
    P2B: "نظام إدارة المراسلات",
    param_generate_corres_num_timing: "توقيت إنشاء رقم المراسلة",
    param_inbox: "صندوق الوارد",
    param_related_adhoc_workflow: "قيم خاصة بمسار توجيه الأرشيف",
    param_related_inbound_workflow: "قيم خاصة بمسار مراسلات الوارد",
    param_related_outbound_workflow: "قيم خاصة بمسار مراسلات الصادر",
    param_webapp_setting: "إعدادات خاصة بتطبيق الويب",
    picklist_filter: "معايير القوائم",
    picklist_items_list: "قائمة القوائم",
    physical_attachment: "المرفقات الصلبة",
    profiles_list: "قائمة المجموعات",
    profile_views: "صلاحيات المجموعة",
    print_range_barcode: "طباعة مجموعة باركود",
    print_specific_barcode: "طباعة باركود معين",
    read_access_group: "مجموعة القراءة",
    reset_barcode: "إعادة تعيين الباركود",
    resubmit: "إعادة إرسال",
    report_filter: "معايير التقرير",
    report_name: "اسم التقرير",
    report_view: "عرض التقرير",
    route: "التوجيه",
    routes: "التوجيهات",
    routing_details: "تفاصيل التوجيه",
    route_orgunit: "مجموعة توجية الوحدة التنظيمية",
    route_user: "مجموعة توجية المستخدمين",
    save_reset: "الحفظ وإعادة الضبط",
    scan_index_group: "مجموعة المسح الضوئي",
    schema_items: "بنود المقطع",
    search: "البحث",
    search_by_metadata: "البحث ببيانات المراسلة",
    search_by_content: "البحث بمحتوى المراسلة",
    search_criteria: "معايير البحث",
    search_corres: "البحث عن المراسلات",
    search_ext_ent: "البحث عن جهات الخارجية",
    search_result: "نتائج البحث",
    search_org_unit: "البحث عن وحدات التنظيمية",
    search_user: "البحث عن مستخدم",
    segment: "مقطع",
    settings: "الأعدادات",
    stamps_list: "قائمة الأختام للوحدات التنظيمية",
    stamps_general_list: "قائمة الأختام العامة",
    stamp_create: "إنشاء ختم",
    stamp_edit: "تعديل ختم",
    submit: "إرسال",
    super_user_selection: "إختيار المديرين الأعلى للنظام",
    taskSearchCirteria: "معايير صندوق المهام",
    task_sendDelayComment: "إرسال تعليق تأخير المهمة",
    tasks: "المهام",
    task_details: "تفاصيل المهمة",
    tasks_complete_multi_reply_routing: "الرد على التوجيهات",
    tasks_complete_multi_routings_replies: "الرد بنتائج التوجيهات",
    tasks_complete_multi_finish_inbound: "نتائج التوجيهات و انهاء الوارد",
    tasks_finishing_list: "قائمة المهام",
    template_list: "القوالب",
    top_criteria: "المعايير الهامة",
    type_schema: "نوع المقطع",
    upload_document: "تحميل الوثيقة",
    user_filter: "معايير المستخدم",
    user_data: "بيانات المستخدم",
    user_preferences: "إعدادت المستخدم",
    userPerferenceOrgunitsRolesSection: "أدوار المستخدم فى الوحدات التنظيمية",
    versions: "إصدارات المستند",
    view: "عرض",
    warning: "تحذير",
    assign_users_profile: "تعيين مستخدمين المجموعة",
    delivery: "مذكرة توقيع الاستلام",
    urgency_notification: "إدارة رسائل التذكير والتصعيد",
    org_unit_G2G: "الجهة الحكومية (G2G)",
    G2G_group: "مجموعة الاستقبال",
    attachment_size: "التحكم في أقصى حجم للملف",
    permission: "الصلاحيات",
    externalApplications: "تطبيقات خارجية",
    ext_ent_search_delegation: "معايير بحث التفويض ",
    choose_weekend_days: "اختيار أيام عطلة نهاية الأسبوع",
    official_vacations: "الاجازات الرسمية",
    add_official_vacations: "إضافة أجازة رسمية",

    AddComment: "إضافة تعليق",
    comments: "التعليقات",
    orgunit_main: "الوحدات التنظيمية ( المستهدفه )",
    orgunit_sec: "الوحدات التنظيمية ( التوجيه و نسخ المطابقة )",
    table_view: "الشكل الجدولي",
    list_view: "الشكل القائمي",
  },

  "----------------- Tables -----------------":
    "----------------- Tables -----------------",
  tbl: {
    action: "الإجراء",
    action_date: "تاريخ الإجراء",
    att_last_modifier: "تم التعديل بواسطة",
    att_last_modify_date: "تاريخ التعديل",
    basic: "الأساسي",
    creation_on: "تاريخ الإنشاء",
    corr_num: "رقم المراسلة",
    corr_type: "نوع المراسلة",
    corres_status: "حالة المراسلة",
    corr_date: "تاريخ المراسلة",
    correspondences: "المراسلات",
    currentPerformer: "المنفذ الحالى (مستخدم/وحدة تنظيمية)",
    date_created: "تاريخ الإنشاء",
    description: "الوصف",
    document_name: "اسم المستند",
    document_type: "نوع المستند",
    DocumentOwner: "اسم المنشئ",
    edit_date: "تاريخ التعديل",
    editor_name: "اسم المستخدم الذي قام بالتعديل",
    entries: "المدخلات",
    fileSize: "حجم الملف",
    fileType: "نوع الملف",
    name: "الاسم",
    of: "من مجموع ",
    order: "الترتيب",
    performer_action: "إجراء المنفذ",
    performer_comment: "تعليق المنفذ",
    performer_username: "اسم المنفذ",
    quantity: "الكمية",
    receiving_entity: "الجهة المستلمة",
    task_receiving_entity: "الجهة المستلمة للمهمة",
    sending_entity: "الجهة المرسلة",
    segment_type: "نوع المقطع",
    sent_date: "تاريخ الإرسال",
    sender_name: "اسم المرسل",
    seq_num_length: "طول الرقم التسلسلي",
    show1to: "عرض من 1 إلى ",
    status: "الحالة",
    subject: "الموضوع",
    task: "المهمة",
    task_comment: "تعليق المهمة",
    task_id: "رقم المهمة",
    task_name: "اسم المهمة",
    task_read_receipt: "إعلام القراءة",
    taskDueDate: "تاريخ أنهاء المهمة",
    type: "النوع",
    value: "القيمة",
    notes: "ملاحظات",
    vacation_name: "اسم الأجازة",
    from_date: "تاريخ من",
    to_date: "تاريخ الى",
  },

  "----------------- Messages -----------------":
    "----------------- Messages -----------------",
  msg: {
    task_submitted: "تم إنهاء المهمة بنجاح",

    routes_sent: "تمت الارسال التوجيه بنجاح",
    sync_success: "تمت المزامنة  بنجاح",
    create_success: "تم الإنشاء بنجاح",
    save_working_hours: "تم حفظ ساعات العمل بنجاح",
    del_success: "تم الحذف بنجاح",
    if_del_holiday: "سيتم حذف هذه العطلة بشكل نهائي",
    delete_draft_corres: "تم حذف المسودة بنجاح",
    login_again: " برجاء تسجيل الدخول مرة أخرى",
    create_ex_success: "تم إنشاء الجهة الخارجية بنجاح",
    update_ex_success: "تم تعديل الجهة الخارجية بنجاح",
    adhoc_create: "تم إنشاء توجيه الأرشيف بنجاح",
    announce_grp_activate_q:
      "سوف تقوم بتفعيل مجموعة التعميم المختارة، إذا قمت بالضغط على زر التفعيل",
    announce_grp_activated: "تم تفعيل مجموعة التعميم بنجاح",
    announce_grp_created: "تم أنشاء مجموعة التعميم بنجاح",
    announce_grp_deactivate_q:
      "سوف تقوم بتعطيل مجموعة التعميم المختارة، إذا قمت بالضغط على زر التعطيل",
    announce_grp_deactivated: "تم تعطيل مجموعة التعميم بنجاح",
    announce_grp_not_available: "لا يوجد مجموعات تعميم",
    announce_grp_updated: "تم تعديل مجموعة التعميم بنجاح",
    announce_grp_users_assigned: "تم تعيين المستخدمين بنجاح",
    are_you_sure: "هل أنت متأكد ؟",
    attachment_failed: "فشل فى التحميل",
    attachment_not_start: "لم يبدأ",
    attachment_success: "تم التحميل",
    attachment_selected_files_errors:
      "لم يتم إضافة الملفات الأتيه فى قائمة التحميل ({{num}}):",
    attachment_uploaded_files_failed:
      "بعض الملفات لم يتم تحميلها كمرفقات ، من فضلك قم بالضغط على زر تحميل الملفات مرة أخرى",
    attachment_uploaded_files_success:
      "تم تحميل الملفات الأتيه كمرفقات ({{num}}):",
    auto_complete_not_found: 'لا توجد نتائج تطابق "{{value}}"',
    barcode_will_reset: "سيتم أعادة تعيين الباركود",
    barcode_reseted: "تم أعادة تعيين الباركود بنجاح",
    cant_delete_corr: "لا يمكن حذف المراسلة",
    cannot_edit_corr_t: "لا يمكنك تعديل المراسلة الأن",
    cannot_edit_corr_tc:
      "جارى إرسال المراسلة ، من فضلك انتظر دقائق قليلة ، ثم قم بالضغط على زر التحديث ، إذا لم يتم إرسال المراسلة بعد مرور فترة من الوقت ، قم بالضغط على التعديل وإرسل المراسلة مرة أخرى",
    cant_have_that_many: "لا يمكنك الحصول علي كل هذا",
    code_exist: "هذا المعرف موجود بالفعل، برجاء استخدام معرف اخر",
    corr_updated: "تم تعديل المراسلة بنجاح",
    create_attachment: "تم إضافة المرفقات بنجاح",
    click_to_hide: "اضغط هنا لاخفاء القائمة",
    click_to_see: "اضغط هنا لعرض القائمة",
    default_task_comment: "تم",
    delete_attachment: "تم حذف المرفقات بنجاح",
    delegation_create_sucessfully: "تم إضافة التفويض بنجاح",
    "delegation_waring-message": "المستخدم لديه بالفعل تفويض في نفس التواريخ",
    delegation_terminate_sucessfully: "تم أنهاء التفويض بنجاح",
    delegation_terminate: " سوف تقوم بأنهاء التفويض",
    delegation_cancel_message: "تم إلغاء التفويض بنجاح",
    delegation_cancel: " سوف تقوم إلغاء التفويض",
    delegation_cancel_sucessfully: "تم إلغاء التفويض بنجاح",
    delegation_cancel_start_days_message_warning:
      "لا يمكن إلغاء التفويض الذي بدأت أيامه",
    delegation_terminate_due_days_message_warning:
      "لا يمكن أنهاء التفويض الذي لم تبدأ ايامه او إنتهت أيامه",
    delegation_mode: "انت الآن على نظام التفويض الخاص بالمستخدم ",
    digital_signature_cancel_timeout:
      "تم إلغاء التوقيع الرقمى بعد إنتظار 2 دقيقة بدون إتخاذ إجراء",
    digital_signature_cancel_user: "تم إلغاء التوقيع الرقمى بواسطة المستخدم",
    digital_signature_install:
      "من فضلك قم بتنصيب التطبيق الخاص بالتوقيع الرقمى ،ثم قم بأعادة تشغيل الحاسب ، ثم قم مرة أخرى بأنهاء المهمة",
    digital_signature_method_not_exist:
      "لا توجد وسيلة للتوقيع رقمياً بهذه الطريقة المختارة",
    en_name_exist: "هذا الاسم الانجليزي موجود بالفعل ، برجاء استخدام اسم اخر",
    ar_name_exist: "هذا الاسم العربي موجود بالفعل ، برجاء استخدام اسم اخر",
    download_modification:
      "قم بتنزيل النموذج أولا ....ثم قم بتحميله مرة أخرى بعد تعديله",
    errorPageOpen:
      "حدث خطأ ما عند تحميل المحتويات الاساسية للصفحة (الرابط بالأسفل)، من فضلك قم بدخول الصفحة مرة أخرى عند طريق الرابط بالأسفل، وإذا حدث الخطأ مرة أخرى من فضلك قم بأخد صورة للصفحة الحالية وقم بإرسالها للدعم الفنى.",
    error_task: "يوجد خطأ بالمهمة رقم:",
    ext_import_step1: "1- تنزيل قالب الجهات الخارجية",
    ext_import_step2:
      "2- كتابة الجهات الخارجية داخل القالب بنفس الترتيب الموجود بالقالب",
    ext_import_step3: "3- تحميل قالب الجهة الخارجية",
    file_maxSize: "حجم الملف لا يجب أن يتعدى",
    file_minSize: "حجم الملف لا يجب أن يقل عن",
    file_maxWidth: "عرض الصورة لا يجب أن يتعدى",
    file_maxHeight: "ارتفاع الصورة لا يجب أن يتعدى",
    file_pattern:
      "تعذر تحميل الملف ، لا يدعم النظام صيغة هذا الملف ، النظام يدعم فقط: {{types}}",
    file_pattern_not:
      "النظام لا يدعم صيغة الملف ، النظام يدعم كل الملفات ماعدا: {{types}}",
    file_size50: "حجم الملف لا يجب أن يتعدى 50 ميجابايت",
    file_type_docx: "ملف غير مقبول, ندعم فقط .docx",
    file_name_maxSize: "عدد أحرف اسم الملف لايجب ان يتعدى الرقم الأتى",
    file_special_char: "اسم الملف لا يجب أن يحتوى على الحروف الأتيه",
    field_cannt0: "هذا الحقل لا يجب أن تكون قيمته 0",
    has_attachment: "توجد مرفقات",
    if_activate: "انت علي وشك تفعيل هذه الوحدة (الوحدات) التنظيمية",
    if_activate_general: "انت علي وشك تفعيل الاحتيار (الاختيارات) المحددة",
    if_deactivate: "انت علي وشك الغاء تعطيل هذه الوحدة (الوحدات) التنظيمية",
    if_deactivate_general: "انت علي وشك تعطيل الاخيار (الاختيارات) المحددة",
    if_download: "إذا اخترت تنزيل, سيتم تنزيل المراسلة",
    if_download_general: "إذا اخترت تنزيل، سيتم تنزيل الملف المختار",
    if_delete_draft_corres: "إذا اخترت حذف، سيتم حذف النسخة المؤقتة للمراسلة",
    if_delete_corres: "إذا اخترت حذف، سيتم حذف المراسلة",
    if_delete_attachment: "إذا اخترت حذف، ستقوم بحذف المرفقات",
    if_delete_all_attachment: "إذا اخترت حذف، ستقوم بحذف جميع المرفقات",
    if_delete_general: "سوف تحذف الاشياء المختارة، إذا قمت بالضغط على زر الحذف",
    if_delete_scaned:
      "سوف تقوم بحذف الصفحة المختارة ، إذا قمت بالضغط على زر الحذف",
    if_delete_all_scaned:
      "سوف تقوم بحذف جميع الصفحات ، إذا قمت بالضغط على زر الحذف",
    if_discard: "إذا اخترت نعم، سيتم تجاهل التغييرات",
    if_terminate_route: "إذا أخترت إيقاف التوجيه، سيتم إيقاف التوجيه",
    if_resubmit: "إذا اخترت إعادة إرسال، سيتم إعادة إرسال المراسلة",
    if_user_change_profile: "انت علي وشك تغيير صورة الملف الشخصي",
    if_user_change_signature: "انت علي وشك تغيير صورة التوقيع",
    if_save: "إذا اخترت حفظ, سيتم حفظ توجيهاتك في جدول التوجيهات",
    if_save_general: "انت علي وشك الحفظ، اضغط الغاء للرجوع",
    if_user_title_delete: "إذا اخترت حذف، سيتم حذف المسمى الوظيفى للمستخدم",
    if_user_title_cannot_delete:
      "لا يمكنك حذف المسمى الوظيفى الوحيد أو الافتراضى",
    import_uploaded: "تم إستيراد نسخة جديدة بنجاح",
    import_success: "تم الاستيراد بنجاح ",
    inbound_delete: "تم حذف الوارد بنجاح",
    inbound_submitted: "تم إرسال الوارد بنجاح",
    inbound_saved: "تم حفظ الوارد بنجاح",
    inbox_no_finishInboundTasks: "لا توجد مهام وارد جديد (نتائج التوجيهات)",
    inbox_no_replyOnRoutingTasks: "لا توجد مهام الرد على التوجيه",
    inbox_no_routingsRepliesTasks:
      "لا توجد مهام الرد على التوجيه (نتائج التوجيهات)",
    input_accept_englisLetterhNumberUnderScore:
      "هذا الحقل لايقبل الا الأتى 0-9 a-z A-Z underscore",
    invalid_login: "خطأ في المستخدم أو كلمة السر",
    invalid_user: "خطأ فى المستخدم ، من فضلك تواصل مع مسئول النظام",
    maxlength: "لا يجب أن يتعدى هذا الحقل {{length}} حرف",
    maxlength4: "لا يجب أن يتعدى هذا الحقل عن 4 حروف",
    maxlength9: "لا يجب أن يتعدى هذا الحقل 9 حروف",
    maxlength16: "لا يجب أن يتعدى هذا الحقل 16 حرف",
    maxlength25: "لا يجب أن يتعدى هذا الحقل 25 حرف",
    maxlength32: "لا يجب أن يتعدى هذا الحقل 32 حرف",
    maxlength64: "لا يجب أن يتعدى هذا الحقل 64 حرف",
    maxlength128: "لا يجب أن يتعدى هذا الحقل 128 حرف",
    maxlength255: "لا يجب أن يتعدى هذا الحقل 255 حرف",
    maxlength512: "لا يجب أن يتعدى هذا الحقل 512 حرف",
    maxlength500: "لا يجب أن يتعدى هذا الحقل 500 حرف",
    minlength4: "لا يجب أن يقل هذا الحقل عن 4 حروف",
    no_attachment: "لا يوجد مرفقات",
    no_commment_found: "لا يوجد تعليق",
    no_corres: "لا توجد مراسلات",
    no_data: "لا توجد بيانات متاحة",
    no_followup: "لا توجد متابعات متاحة",
    no_history: "لا توجد إجراءات متاحة",
    no_notifications: "لا توجد إشعارات متاحة",
    no_profiles: "لا توجد مجموعات متاحة",
    no_routes: "لا يوجد توجيهات",
    no_searchResult: "لا توجد نتائج",
    no_statistics: "لا توجد أحصائيات",
    no_subject: "لا يوجد عنوان",
    no_tasks: "لا توجد مهام",
    notify_Announcement:
      "يرجى العلم أن المستخدم {{user_description}} قد قام بإرسال تعميم إليك ، تفاصيل التعميم كما يلى:",
    notify_CCUser:
      "يرجى العلم أنه قد تم استلام نسخة مطابقة للعلم فقط ، تفاصيل المراسلة كما يلى:",
    notify_clickHere: "لمراجعة المراسلة يرجى الضغط هنا",
    notify_Decision:
      "يرجى العلم أن المستخدم {{user_description}} قد قام بإرسال قرار إليك ، تفاصيل القرار كما يلى:",
    notify_Delegation:
      "يرجى العلم أن قد تم تعيين تفويض جديد لك من مستخدم {{user_description}} خلال الفترة من {{start_date}} إلى {{end_date}}",
    notify_IssuerFinalAprroval:
      "يرجى العلم أن المستخدم {{user_description}} قد قام باعتماد المراسلة التالية والتى قمت بإنشائها:",
    notify_period: "يجب إدخال أرقام من 1 إلى 365",
    notify_ReadReceipt:
      "يرجى العلم أنه قد تم قراءة مهمة {{task_name}} بواسطة {{user_description}} و التي تتعلق بالمراسلة التالية:",
    notify_RejectInternalToApproval:
      "يرجى العلم أن المستخدم {{user_description}} قد قام برفض المراسلة الداخلية التالية و التي قد قمت باعتمادها:",
    notify_RouteCC:
      "يرجى العلم أنه قد تم استلام نسخة مطابقة للعلم فقط ، تفاصيل المراسلة كما يلى:",
    notify_RouteFyi:
      "يرجى العلم أنه قد تم استلام مراسلة جديدة للعلم فقط ، تفاصيل المراسلة كما يلى:",
    notify_SendAdHoc:
      "يرجى العلم أنه قد تم إرسال مهمة {{task_name}} اليك بواسطة {{user_description}} ، من فضلك قم بإتخاذ إجراء على المهمة و التي تتعلق بالمراسلة التالية:",
    notify_TaskAcquire:
      "يرجى العلم أنه قد تم قبول مهمة {{task_name}} بواسطة {{user_description}} و التي تتعلق بالمراسلة التالية:",
    notify_TaskDelayComment:
      "يرجى العلم أنه قد سوف يتم تأخير الرد على مهمة {{task_name}} بواسطة {{user_description}} و التي تتعلق بالمراسلة التالية:",
    orgunit_deactivate: "تم تعطيل الوحدة التنظيمية بنجاح",
    orgunit_activate: "تم تفعيل الوحدة التنظيمية بنجاح",
    orgunit_create: "تم اضافة الوحدة التنظيمية بنجاح",
    orgunit_outbound_save: "تم حفظ مستخدموا الصادر بنجاح",
    orgunit_inbound_save: "تم حفظ مستخدموا الوارد بنجاح",
    orgunit_updated: "تم تعديل الوحدة التنظيمية بنجاح",
    orgunit_users_save: "تم حفظ مستخدموا الوحدة التنظيمية بنجاح",
    outbound_delete: "تم حذف الصادر بنجاح",
    outbound_submitted: "تم أنهاء الصادر بنجاح",
    outbound_saved: "تم حفظ الصادر بنجاح",
    outbound_template_download:
      "تم تنزيل النموذج بنجاح، برجاء تحميل النسخة الجديدة",
    outbound_template_upload: "تم تحميل النموذج بنجاح",
    outbound_template_create: "تم اضافة القالب بنجاح",
    outbound_template_update: "تم تعديل القالب بنجاح",
    outbound_template_delete: "تم حذف القالب بنجاح",
    pls_select: "من فضلك حدد منطقة للقص",
    pls_add_files: "لا يوجد ملفات، برجاء اضافة ملفات",
    start_digital_signature_process:
      "تم إرسال ملف المراسلة إلى جوالك لاعتمادها بواسطة التوقيع الألكترونى ، من فضلك قم بالتوقيع فى خلال دقيقتين",
    q_do_want_continue_digital_signature_process:
      "لقد مرت دقيقتين منذ بدأت التوقيع الألكترونى ، هل تريد أستكمال عملية التوقيع الألكترونى؟",
    q_do_want_save_default_inbox_list: "هل تريد تغيير طريقة عرض صندوق المهام؟",
    q_do_want_save_default_inbox_table: "هل تريد تغيير طريقة عرض صندوق المهام؟",
    report_generated: "تم إنشاء التقرير بنجاح",
    report_no_users_available: "لا يوجد مستخدمين بتلك الوحدة التنظيمية",
    required: "يجب إدخال هذا الحقل",
    requiredWithoutSpecial:
      "يجب إدخال هذا الحقل ، يمكنك إدخال ( الحروف والارقام العربية ، الحروف والارقام الانجليزية ، المسافة ، _ ، - ، .)",
    route_added: "تم اضافة توجيه بنجاح",
    route_to: "التوجيه الي ",
    route_before: " اضيف مسبقاً",
    routed_before: "تم الإرسال من قبل",
    routed_not_before: "لم يتم الإرسال من قبل",
    routes_routed_before:
      "بعض التوجيهات المضافة تم إرسالها مسبقاً من قبل مستخدم أخر ، قم بالضغط مرة أخرى على زر إرسال التوجيه للإرسال.",
    route_delete: "تم حذف التوجيه بنجاح",
    route_update: "تم تعديل التوجيه بنجاح",
    route_terminated: "تم إيقاف التوجيه بنجاح",
    save_route: "هل تريد حفظ التوجيه ؟",
    segment_type_added_before: "تم إضافة نوع هذا المقطع من قبل",
    select_orgunit:
      "قم بإختيار وحدة تنظيمة من شجرة البيانات لتحصل على المراسلات",
    select_new_period: "قم بإختيار فترة زمنية جديدة لتحصل على الاحصائيات",
    select_user: "اختر مستخدم",
    select_picklist_type: "برجاء اختيار نوع قائمة",
    session_timeout_login:
      "لقد أنتهى الوقت المسموح للجلسة، من فضلك قم بتسجيل الدخول مرة أخرى لتجديد المدة، أو قم بتسجيل الخروج",
    session_timeout_sso:
      "لقد أنتهى الوقت المسموح للجلسة ، من فضلك أنتظر لحظات قليلة",
    short_number_exist: "هذا الرقم موجود بالفعل، برجاء استخدام رقم اخر",
    some_external_exist_short:
      "يوجد بعض الجهات الخارجية المشابهة لهذا الرقم المختصر ،",
    some_external_exist_en: "يوجد بعض الجهات الخارجية المشابهة لهذا الاسم ،",
    some_external_exist_ar: "يوجد بعض الجهات الخارجية المشابهة لهذا الاسم ،",
    something_wrong_happened:
      "حدث خطأ ما عند أحضار بعض البيانات، من فضلك حاول مرة أخرى",
    stamp_orgunit_duplicated:
      "الوحدة التنظيمية المختارة لديها ختم بالفعل ، من فضلك قم بإختيار وحدة تنظيمية أخرى",
    stamp_if_delete: "إذا اخترت حذف، ستقوم بحذف ختم الوحدة التنظيمية",
    stamp_create: "تم إنشاء ختم الوحدة التنظيمية بنجاح",
    stamp_edit: "تم تعديل ختم الوحدة التنظيمية بنجاح",
    stamp_delete: "تم حذف ختم الوحدة التنظيمية بنجاح",
    stamp_save_settings: "تم حفظ الأعدادات",
    task_finish_q: "إذا إخترت أنهاء، سيتم أنهاء المهمة",
    task_completed: "تم أنهاء المهمة بنجاح",
    tasks_completed: "تم أنهاء المهام بنجاح",
    tasks_multi_finished_failed:
      "فشل أنهاء بعض المهام من فضلك حاول مرة أخرى ، لو حدثت المشكلة مرة أخرى قم بإرسال رقم المهمة للدعم الفنى",
    task_already_completed: "تلك المهمة أنهيت من قبل",
    task_overdue: "مهمة متأخرة",
    task_previous_comment: "تعليق المستخدم السابق :",
    task_complete_not_start: "لم تبدأ",
    task_complete_success: "تم الأنهاء بنجاح",
    task_complete_failed: "فشل فى الأنهاء",
    task_delay_comment_sent: "تم إرسال تعليق تأخير المهمة بنجاح",
    today_future:
      " يجب أن تكون القيمة المدخلة تاريخ اليوم أو تاريخ في المستقبل",
    the_corr: " المراسلة",
    twoFactorAuthenticationWaiting:
      "من فضلك قم بالموافقة على المصادقة الثنائية من خلال تطبيق الموبايل",
    unauthorized: "ليس لديك الصلاحية لفتح تلك الصفحة",
    unauthorized_home_page1:
      "من فضلك قم بتغيير الصفحة الرئيسية المفضلة من إعدادات المستخدم",
    unauthorized_home_page2: "للذهاب لصفحة إعدادات المستخدم أضغط هنا",
    unauthorized_home_page3:
      "أو قم بالضغط على صورة حسابك ثم قم بإختيار إعدادات المستخدم من القائمة المنسدلة",
    update_attachment: "تم تعديل المرفقات بنجاح",
    upload_first: "قم بتحميل الملف أولا للسماح بإضافة بيانات المراسلة",
    upload_first_attachment: "قم بتحميل الملف أولا للسماح بإضافة المرفقات",
    user_data_save: "تم حفظ بيانات المستخدم بنجاح",
    userPreference_noOrgUnitData: "لم يتم إضافة هذا المستخدم فى أى دور",
    userPreference_orgunitDuplicate:
      "تم إضافة الوحدة التنظيمية ({{data}}) من قبل ، يمكنك إلغاء الإضافة وأختيارها من القائمة المنسدلة",
    userPerference_role_add: "تم إضافة المستخدم إلى الوحدة التنظيمية بنجاح",
    userPerference_role_save: "تم حفظ الادوار بنجاح",
    super_admin_save: "تم حفظ بيانات المديرين الأعلى للنظام بنجاح",
    wrong_email_format: "خطأ في هيئة البريد الالكتروني",
    wrong_phone_format:
      "خطأ في هيئة رقم الهاتف برجاء استخدام الارقام من 0 الي9 فقط",
    wrong_fax_format:
      "خطأ في هيئة رقم الفاكس برجاء استخدام الارقام من 0 الي 9 فقط",
    you_not_assign: "ليس لديك صلاحية لإنشاء صادر جديد",
    you_not_assign_inbound: "ليس لديك صلاحية لإنشاء وارد جديد",
    you_should_select: "برجاء اختيار نسخة مؤقتة واحدة علي الاقل",
    you_will: "سوف تقوم بـ ",
    parameter_save: "تم حفظ التعديلات",
    outbound_task_confirem_title:
      "سوف يتم ارسال المراسلة من خلال (مكتب البريد)",
    outbound_task_confirem_contant: "لذلك .. لابد من طباعة هذه المراسلة الآن",
    outbound_task_confirm_contant:
      "سوف تقوم بإرسال المراسة عن طريق البريد ، من فضلك قم بطباعة المراسلة ، ثم قم بالضغط على المربع",
    hint_keywords: "أضغط على زر الإدخال لإضافة كلمة مفتاحية جديدة",
    error_title: "خطأ",
    error_message: "يرجى الاتصال بمسؤول النظام",
    add_picklist: "تم إضافة عنصر القائمة بنجاح",
    edit_picklist: "تم تعديل عنصر القائمة بنجاح",
    pickList_activate: "تم تفعيل عنصر القائمة بنجاح",
    pickList_deactivate: "تم تعطيل عنصر القائمة بنجاح",
    pickList_delete: "تم حذف عنصر القائمة بنجاح",
    pickList_used_delete:
      "لايمكن حذف عنصر القائمة لأنه مستخدم فى بعض المراسلات",
    correspondence_add: "تم إضافة مخطط رقم المراسة بنجاح",
    correspondence_save: "تم حفظ مخطط رقم المراسلة بنجاح",
    correspondence_deleted: "تم حذف رقم المراسلة بنجاح",
    corres_deleted: "تم حذف المراسلة بنجاح",
    fill_require_data: "يرجى تعبئة البيانات المطلوبة",
    app_profile_delete: "تم حذف المجموعة بنجاح",
    app_profile_create: "تم إضافة المجموعة بنجاح",
    app_profile_update: "تم تعديل المجموعة بنجاح",
    app_profile_users_assigned: "تم تعيين المستخدمين بنجاح",
    send_message_succ: "تم إرسال الرسالة بنجاح",
    delivery_note_created: "تم إضافة توقيع الإستلام بنجاح",
    delivery_note_delete_q: "إذا اخترت حذف ، ستقوم بحذف توقيع الإستلام",
    delivery_note_delete_add_q:
      "إذا اخترت حذف ، ستقوم بحذف توقيع الإستلام القديم وإضافة جديد",
    delivery_note_deleted: "تم حذف توقيع الإستلام بنجاح",
    delivery_note_not_available: "لم يتم إضافة توقيع إستلام",
    if_Sync_users: "هل تحتاج الى مزامنة المستخدمين فى نظامك ؟",
    you_not_assign_delivery: "ليس لديك الصلاحية لانشاء توقيع الاستلام",
    you_not_assign_delete_delivery: "ليس لديك الصلاحية لحذف توقيع الإستلام",
    no_action: "لا يوجد إجراءات",
    outbound_task_hasphysical: "يرجى ملاحظة وجود مرفقات مادية",
    outbound_task_enable_g2g:
      "هذه الجهة الخارجية غير معرفة من ضمن جهات التراسل الحكومي الالكتروني ( G2G )",
    outbound_task_hasElectronic: "هل تريد ارسال المرفقات الالكترونيه",
    outbound_task_hasElectronicwarning:
      "يدعم نظام التراسل الحكومي مرفقات من نوع PDF و Tiff فقط",
    attachment_size_error: "حجم الملف لا يجب أن يكون من 1 إلى 200 (MB)",
    outbound_task_reload: "من فضلك قم بإعادة تحميل المراسلة",
    task_unauthorized_completed: "تلك المهمة ليس لديك الصلاحية عليها",
    task_task_taked: "تم قبول هذه المهمة من قبل شخص اخر",
    hint_readReceipt:
      "استلام بريد الكتروني عند قراءة المهمة بواسطة مستلم المهمة",
    orgunit_quickly_create: "تم اضافة المستخدمين إالى الوحدة التنظيمية بنجاح",
    inlinepassword_mode: "انت الآن مسجل دخول بالمستخدم",
    save_weekly_holiday_error: "خطأ فى حفظ أيام العطلة الإسبوعية",
    save_annual_holiday_error: "خطا فى حفظ الأجازة الرسمية",
    save_annual_holiday: "تم حفظ الأجازة بنجاح",
    update_annual_holiday: "تم تعديل الأجازة بنجاح",
    delete_annual_holiday: "تم حذف الأجازة بنجاح",
    delete_annual_holiday_error: "يوجد خطأ فى حذف الاجازة",
    if_delete_annual_holiday: "هل انت تريد حذف هذه الأجازة ؟",
    save_correspondance_note: "تم حفظ التعليق بنجاح",
    no_notes: "لا توجد تعليقات متاحة",
    delete_urgancy_notification: "تم حذف الإشعار بنجاح",
    update_urgancy_notification: "تم تعديل الإشعار بنجاح",
    add_urgancy_notification: "تم إضافة الإشعار بنجاح",
    delegation_update_sucessfully: "تم تعديل التفويض بنجاح",
    work_done: "تم عمل اللازم",
    users_save: "",
    create_delivery: "",
  },

  "----------------- Main Menu -----------------":
    "----------------- Main Menu -----------------",
  mnu: {
    translation_manager: "إدارة الترجمة",
    create_delegation: "إنشاء تفويض",
    view_delegation: "عرض بيانات التفويض",

    sla: "اتفاقية مستوى الخدمة",
    task_management: "إدارة المهام",
    accessibility_priviliges: "صلاحيات التطبيق",
    announcements_groups: "مجموعات التعاميم",
    app_parameters: "معايير التطبيق",
    barcode: "الباركود",
    corres_schema: "مخطط رقم المراسلة",
    dashboard: "لوحة المعلومات",
    external_entity: "الجهات الخارجية",
    inbox: "صندوق المهام",
    inbox_g2g: "وارد G2G",
    inbound: "إنشاء وارد",
    g2g_task: "مهمة G2G",
    organization_unit: "الوحدات التنظيمية",
    outbound: "إنشاء صادر",
    outbound_templates: "قوالب الصادر",
    picklists: "القوائم",
    reports: "التقارير",
    users_preferences: "اعدادات المستخدمين",
    delegation: "التفويض",
    auditing: "المراقبة",
    calendar: "التقويم",
    search: "البحث عن مراسلات",
    created_by_me: "تم الإنشاء بواسطتي",
    super_user_management: "إدارة المديرين الأعلى للنظام",
    stamps: "الأختام",
    urgency_notification: "الإشعارات العاجله",
  },

  "----------------- Page Header -----------------":
    "----------------- Page Header -----------------",
  ph: {
    accessibility_priviliges: "صلاحيات التطبيق",
    announcements_groups: "مجموعات التعاميم",
    app_parameters: "معايير التطبيق",
    app_notifications: "إشعارات التطبيق",
    barcode: "الباركود",
    corres_schema: "مخطط رقم المراسلة",
    dashboard: "لوحة المعلومات",
    external_entity: "الجهات الخارجية",
    inbox: "صندوق المهام",
    inbox_g2g: "وارد G2G",
    inbound: "الوارد",
    g2g_task: "مهمة G2G",
    organization_unit: "الوحدات التنظيمية",
    outbound: "الصادر",
    outbound_templates: "قوالب الصادر",
    picklists: "القوائم",
    reports: "التقارير",
    user_preferences: "إعدادات المستخدم",
    users_preferences: "اعدادات المستخدمين",
    delegation: "التفويض",
    auditing: "المراقبة",
    calendar: "التقويم",
    search: "البحث عن مراسلات",
    created_by_me: "تم الإنشاء بواسطتي",
    super_user_management: "إدارة المديرين الأعلى للنظام",
    stamps: "الأختام",
    urgency_notification: "الإشعارات العاجله",
  },

  "----------------- Picklist -----------------":
    "----------------- Picklist -----------------",
  pk: {
    announcment_group: "مجموعة التعميم",
    approval_subtype: "الموافقات",
    correspondence_type: "نوع المراسلة",
    document_type: "نوع الملف",
    escalation_performer: "منفذ التصعيد",
    external_entity_classification: "تقسيمات الجهات الخارجية",
    external_entity_sending_method: "طرق ارسال الجهات الخارجية",
    history_status: "حالات سجل الاجراءات",
    inbound_source: "مصادر الوارد",
    language: "اللغة",
    org_unit_level: "مستوي الوحدة التنظيمية",
    outbound_sending_type: "انواع ارسال الصادر",
    outbound_types: "انواع الصادر",
    physical_attachment_type: "انواع المرفقات الصلبة",
    rejection_folder: "مجلد الرفض",
    rejection_reason: "سبب الرفض",
    required_action: "الاجراء المطلوب",
    reviewer_actions: "اجراءات المراجع",
    security_level: "مستوي السرية",
    sender_action: "اجراء المرسل",
    sender_reject_outbound: "مرسل رفض الصادر",
    stamp_options: "انواع الاختام",
    status: "الحالة",
    task_subject: "اسم المهمة",
    urgency_level: "مستوي الاهمية",

    segment_Inbound: "وارد خارجي",
    segment_Outbound: "صادر خارجي",
    segment_Internal: "مراسلات داخلية",
    segment_InternalAnnouncement: "مراسلات داخلية (تعميم)",
    segment_InternalDecision: "مراسلات داخلية (قرار)",
    segment_InternalMeeting: "مراسلات داخلية (محاضر إجتماعات)",
  },

  "----------------- ToolTip -----------------":
    "----------------- ToolTip -----------------",
  ttp_search: "البحث",

  "----------------- Dynamic -----------------":
    "----------------- Dynamic -----------------",
  adhoc: "توجيه أرشيف",
  Adhoc: "توجيه أرشيف",
  all: "الكل",
  All: "الكل",
  Announcement: "تعميم",
  "Application Paramters Management": "إدارة معايير التطبيق",
  "Approve Outbound": "اعتماد الصادر",
  archived: "الأرشيف",
  Browse: "تصفح",
  "Change file": "تغيير الملف",
  "Create Inbound": "إنشاء الوارد",
  "Create Outbound": "إنشاء الصادر",
  Custom: "مخصص",
  dashboard: "لوحة المعلومات",
  Draft: "المسودة",
  "Edit Inbound": "تعديل الوارد",
  "Edit Draft Outbound": "تعديل الصادر",
  From: "من",
  generic: "عام",
  global_language_en: "اللغة الإنجليزية",
  global_language_ar: "اللغة العربية",
  "Hide Advanced Search": "إخفاء البحث المتقدم",
  Hybrid: "مختلط",
  inbound: "الوارد",
  Inbound: "وارد خارجي",
  inbox: "صندوق المهام",
  "Incoming External": "وارد خارجي",
  Internal: "مراسلات داخلية",
  isDueDate: "متأخر التنفيذ",
  "New Inbound": "وارد جديد",
  "Organization Unit": "الوحدات التنظيمية",
  "Organization Unit - View": "عرض الوحدة التنظيمية",
  "Organization Unit Form": "الوحدة التنظيمية",
  "Org Unit Manager": "مدير الوحدة التنظيمية",
  "External Entity": "الجهات الخارجية",
  outbound: "الصادر",
  Outbound: "صادر خارجي",
  "Outgoing External": "صادر خارجي",
  overdue: "متأخر",
  "Parent Organization Unit": "الوحدة التنظيمية الاعلي",
  "Rejected Inbound": "وارد مرفوض",
  "Rejected Outbound": "صادر مرفوض",
  "Rejected Routing": "توجيه مرفوض",
  "Reply Adhoc": "الرد المخصص",
  "Reply Routing": "رد التوجيه",
  "Review Outbound": "مراجعة الصادر",
  "Routing Replies": "ردود التوجيهات",
  Search: "البحث",
  "Send For Approval": "إرسال للاعتماد",
  "Send For Review": "إرسال للمراجعة",
  "Send Outbound": "إرسال الصادر",
  "Show Advanced Search": "إظهار البحث المتقدم",
  Submit: "إرسال",
  System: "نظام",
  task_name: "اسم المهمة",
  To: "الي",
  Today: "هذا اليوم",
  "This Month": "هذا الشهر",
  "This Week": "هذا الأسبوع",
  "View Routing": "عرض التوجيه",
  User: "مستخدم",
  Month: "شهر",
  Day: "يوم",
  Hour: "ساعة",
  "Send For Approval skip Review": "تخطي المراجعة و ارسال إلى الاعتماد",

  Saturday: "السبت",
  Sunday: "الأحد",
  Monday: "الاثنين",
  Tuesday: "الثلاثاء",
  Wednesday: "الأربعاء",
  Thursday: "الخميس",
  Friday: "الجمعة",

  notification_desc: "arDesc",
  Desc: "DescAr",
  external_enitity_desc: "descAr",
  general_enitity_desc: "descAr",
  ext_entity_desc: "extEntityDescAr",
  org_unit_desc: "orgUnitDescAr",
  org_unit_desc2: "orgUnitArabicDesc",
  announcement_desc: "nameAr",
  picklist_label: "picklistArLabel",
  route_description: "arDescription",
  routeFromOrganizationUnit: "routeFromOrganizationUnitAr",
  routeToOrganizationUnit: "routeToOrganizationUnitAr",
  dd_userTitle: "arUserTitle",
  user_title_ae: "arabicTitle",
  corrStatusPickListDescription: "corrStatusPickListArDescription",
  corrTypePickListDescription: "corrTypePickListArDescription",
  sendingEntityDescription: "sendingEntityArDescription",
  task_action_description: "taskActionArName",
  receivingEntityDescription: "receivingEntityArDescription",
  user_description: "arDescription",
  orgunit_allowedCode: "arName",
};
