import { AppConstantType } from "./app-constant-type";

export const englishLabels: AppConstantType = {
  "----------------- Labels -----------------":
    "----------------- Labels -----------------",
  lbl: {
    or: "or",
    civil_id: "Civil ID",
    creator: "Creator",
    delegate_all: "Delegate All",
    add_role: "Add Role",
    assignee: "Assignee",
    acquired_date: "Acquired Date",
    is_Breach: "is breach ? ",
    total_Breached: "Total Breached",
    total: "Total",
    currnet_tasks_st: "Current Tasks Statistics",
    sla_type: "SLA Type",
    sla_time: "SLA Time",
    day: "Day",
    time_start: "Start Time",
    end_time: "End Time",
    postponedToDate: "Postponed To Date",
    postponedEndDate: "Postponed End Date",
    task_start_date: "Task Start Date",
    current_user: "Current User",
    is_delegated_before: "Is Delegated Before",
    is_postponed_before: "Is Postponed Before",
    about_version: "Version ",
    about_build: "Build ",
    about_release_date: "Release Date ",
    about_rights1: "2019 © International Turnkey Systems.",
    about_rights2: "All rights reserved.",
    about_visit: "For more information, please visit",
    active: "Active",
    not_active: "Not Active",
    adhoc_user: "User",
    adminNormalUsers: "Delete Normal Users",
    adminSecretUsers: "Delete Secret Users",
    adminTopSecretUsers: "Delete Top Secret Users",
    announce_grp: "Announcment Group",
    announce_grp_all_users: "All Users",
    announce_grp_code: "Announcment Group Code",
    announce_grp_email: "Announcment Group Email",
    announce_grp_name: "Announcment Group Name",
    announce_grp_name_ar: "Announcment Group Name Arabic",
    announce_grp_name_en: "Announcment Group Name English",
    announce_grp_status: "Status",
    announce_grp_users: "Announcment Group Users",
    archived: "Archived",
    approve: "Approve",
    approver_title: "Approver Title",
    approvers_titles: "Previous Approvers List",
    approveforward: "Approve and Forword",
    approve_action: "Approve Outbound - Default Action",
    approve_digital_signature: "Sign with Digital Signature",
    approve_digital_signature_method: "Digital Signature Through",
    approve_digital_signature_position: "Digital Signature Position",
    approve_text: "نص الاعتماد",
    arabic_name: "Arabic Name",
    authenticating: "Signing in ....",
    average_duration_task: "Average Duration Task",
    appParam_AdhocEnabled: "Enable Adhoc",
    appParam_AdhocEnabled_True: "Enable",
    appParam_AdhocEnabled_False: "Disable",
    appParam_AdhocSendToAll:
      "Select adhoc receiver from specific list based on the sender's organization unit settings",
    appParam_AdhocSendToAll_False:
      "Yes, A specific list will will be appeared to select from it.",
    appParam_AdhocSendToAll_True:
      "No, All users field will will be appeared to select from it.",
    appParam_ContentSearchEnabled: "Enable Search By Content",
    appParam_ContentSearchEnabled_True: "Yes",
    appParam_ContentSearchEnabled_False: "No",
    appParam_onlineEditor: "Enable Online Editor Application",
    appParam_digitalSignature: "Enable Digital Signature Application",
    appParam_DigitalSignatureMandatory: "Digital Signature Mandatory",
    appParam_DigitalSignatureType: "Digital signature through",
    appParam_GeneralStampOnly:
      "Using the general stamp on all outbound correspondences",
    appParam_GeneralStampOnly_True:
      "Yes, The general stamp will be used on all outbound correspondences",
    appParam_GeneralStampOnly_False:
      "No, The user will select between the general stamp and the organization unit",
    appParam_InboundOCREnabled:
      "Enable optical character recognition (OCR) when creating inbound",
    appParam_InboundOCREnabled_True:
      "Yes, The text of content will be extracted and will be shown to the user for editing and saving when sending the correspondence",
    appParam_InboundOCREnabled_False:
      "No, We will send the correspondence to approval directly without extracting the text, but the correspondences will not appear in content search result",
    appParam_MakeTaskActionFromInbox:
      "Take action(Reply on Routing) of the view replies task  from inbox page.",
    appParam_MakeTaskActionFromInbox_True: "Yes",
    appParam_MakeTaskActionFromInbox_False: "No",
    appParam_OutboundMultipleReceivingEnabled:
      "Send outbound correspondence (External or Internal) to multiple enities at once.",
    appParam_OutboundMultipleReceivingEnabled_True: "Yes",
    appParam_OutboundMultipleReceivingEnabled_False: "No",
    appParam_ShowOutboundCorrespondenceDate:
      "Entering the value of Corre. Date from Outbound Create Page",
    appParam_ShowOutboundCorrespondenceDate_True:
      "Yes, The field of Corre. Date will be appeared in Outbound Create Page",
    appParam_ShowOutboundCorrespondenceDate_False:
      "No, The field of Corre. Date will be hidden in Outbound Create Page, and Its value will be equal to Final Approval Date",
    appParam_StampSenderbasedonFinalApproval:
      "Sender's stamp based on final approval",
    appParam_StampSenderbasedonFinalApproval_True:
      "Final approval organization unit stamp",
    appParam_StampSenderbasedonFinalApproval_False:
      "Initiator organization unit stamp",
    appParam_TwoFactorAuthenticationEnabled:
      "Enable Two Factor Authentication with login to system",
    appParam_WebappVersion: "Web Application Version Number",
    br_auto_move: "Auto Move Forward",
    br_current_year: "Current Year",
    br_no: "Barcode Number",
    br_print_range_from: "Barcode Number (From)",
    br_print_range_to: "Barcode Number (To)",
    br_print_range_current: "Current Barcode",
    br_start_no: "Barcode Start Number",
    br_year: "Barcode year",
    by: "By",
    barcode: "Barcode",
    both: "Both",
    cancel: "Cancel",
    cc_external: "CC External",
    cc_internal: "CC Internal",
    cc_list: "CC List",
    change_urgency: "Change Urgency",
    choose_period: "Choose Duration",
    classification: "Classification",
    comment: "Comment",
    contributorNormalUsers: "Edit Normal Users",
    contributorSecretUsers: "Edit Secret Users",
    contributorTopSecretUsers: "Edit Top Secret Users",
    consumerNormalUsers: "Read Access Normal Users",
    consumerSecretUsers: "Read Access Secret Users",
    consumerTopSecretUsers: "Read Access Top Secret Users",
    copy_right: "All Rights Reserved &copy; 2018",
    copy_right17: "Copy Right &copy; 2018",
    correspondence: "Correspondence",
    corr_date: "Correspondence Date",
    corres_date_from: "Correspondence Date From",
    corres_date_to: "Correspondence Date To",
    corr_details: "Correspondence Details",
    corr_number: "Number",
    corr_status: "Correspondence Status",
    corr_subject: "Correspondence Subject",
    corr_types: "Type",
    correspondence_type: "Correspondence Type",
    created_by_me: "Created By Me",
    create_out_action: "Create Outbound - Stamp Option default value",
    create_out_def_template: "Create Outbound - Default Template",
    create_out_doc_default: "Create Outbound - Document Type Default Value",
    creation_date: "Creation Date",
    creation_date_from: "Creation Date From",
    creation_date_to: "Creation Date To",
    date_from: "Date (From)",
    date_to: "Date (To)",
    default: "Default",
    deleted: "Deleted",
    delete_all: "Delete All",
    delete_selected: "Delete Selected",
    description: "Description",
    document_type: "Document Type",
    duration: "Duration",
    email: "Email",
    end_task_date: "End Task Date",
    english_name: "English Name",
    enter_comment: "Enter Comment",
    error_type: "Error Type",
    escalation: "Escalation Messages",
    escalation_performer: "Escalation Performer",
    expected_reply_date: "Expected Reply Date",
    external: "External",
    external_entity: "External Entity",
    ext_ent_classification: "External Entity Classification",
    ext_ent_name: "External Entity Name",
    ext_ref_num: "External Reference Number",
    false: "No",
    fax_number: "Fax Number",
    file_content: "File Content",
    file_name: "File Name",
    final_approv_org_unit: "Final Approval Organization Unit",
    final_approve_ext_out:
      "Restrict final approval of outbound for specefic list of external entities",
    final_approve_int_out:
      "Restrict final approval of  outbound for a specefic list of internal org units",
    finish: "Finish",
    forwardToOrgunit: "Forward to OrgUnit",
    from_local_file: "From Local File",
    from_template: "From Template",
    general: "General",
    not_general: "OrgUnit",
    g2g_group: "Inbound Group (G2G)",
    gen_announce_schema:
      "Generate Correspondence Sequence Number Based on Schema - Announcement",
    gen_corr_num_acquis_info1:
      "Generate the inbound correspondence number only after the acquisition of the receiving entity org unit for this correspondence",
    gen_corr_num_acquis_info2:
      "Generate the inbound correspondence number as soon as it is generated from archiving unit",
    gen_corr_num_schema_info1:
      "Reset the serial number of correspondence with each change on the correspondence number schema item",
    gen_corr_num_schema_info2: "Reset the serial number only once each year",
    gen_inbound_schema:
      "Generate Correspondence Sequence Number Based on Schema - Inbound",
    gen_internal_schema:
      "Generate Correspondence Sequence Number Based on Schema - Internal",
    gen_out_approv_info1:
      "Generate the outbound correspondence number only after the final approval of this correspondence",
    gen_out_approv_info2:
      "Generate the outbound correspondence number once it is issued by the issuer",
    gen_out_send_bas_info1:
      "<b>Initiation Organization Unit:</b> means that the sender is that of the Initiation organization unit of this outbound",
    gen_out_send_bas_info2:
      "<b>Final Approval Organization Unit:</b> means that the sender is that of the final approval organization unit of this outbound",
    gen_outbound_schema:
      "Generate Correspondence Sequence Number Based on Schema - Outbound",
    grant_access_parent: "Grant Access To Parent Organization Unit",
    inb_search_type_action: "Inbound Search - Inbound Type default value",
    inboundRoutingNormalUsers: "Inbound Routing Normal Users",
    inboundRoutingSecretUsers: "Inbound Routing Secret Users",
    inboundRoutingTopSecretUsers: "Inbound Routing Top Secret Users",
    inboundRoutingNormalOrgunit: "Inbound Routing Normal OrgUnit",
    inboundRoutingSecretOrgunit: "Inbound Routing Secret OrgUnit",
    inboundRoutingTopSecretOrgunit: "Inbound Routing Top Secret OrgUnit",
    inboundCCNormalUsers: "Inbound CC Normal Users",
    inboundCCSecretUsers: "Inbound CC Secret Users",
    inboundCCTopSecretUsers: "Inbound CC Top Secret Users",
    inboundCCNormalOrgunit: "Inbound CC Normal OrgUnit",
    inboundCCSecretOrgunit: "Inbound CC Secret OrgUnit",
    inboundCCTopSecretOrgunit: "Inbound CC Top Secret OrgUnit",
    inbound_sender_name: "Inbound Sender Name",
    inbound_cc_email_option: "Inbound CC Email Option",
    inbound_receive_final_route: "Inbound Receive Final Route",
    inbound_routing_user: "Inbound Routing User",
    index_user: "Index User",
    initiation_org_unit: "Initiation Organization Unit",
    initiatorUsers: "Initiator Users",
    internal: "Internal",
    internal_entity: "Internal Entity",
    is_general: "Is General",
    is_active: "Is Active",
    is_deactivatable: "Is Deactivatable",
    issuer_entity: "Issuer Entity",
    KB: "KB",
    keywords: "Keywords",
    no_data: "Invalid Data",
    language: "Language",
    loading: "Loading....",
    move_up: "Move Up",
    move_down: "Move Down",
    name: "Name",
    no: "No",
    notactive: "Not Active",
    notifications: "Notifications",
    notify_cleaner_days:
      "Max period for keeping the notification before deletion (Days)",
    notify_receive_route: "Notify Receive Route",
    notify_outbound_receive_final: "Notify Outbound Receive Final",
    need_reply: "Need Reply",
    new_inbound_action: "New Inbound Received - Default Action",
    number: "Number",
    number_completed_tasks: "Number of Completed Tasks",
    ocr_text: "Correspondence Content Text",
    org_unit: "Organization Unit",
    org_unit_approver_next: "Organization Unit Next Approver",
    org_unit_code: "Org Unit Code",
    org_unit_email: "Org Unit Email",
    org_unit_level: "Organization Unit Level",
    org_unit_manager: "Org Unit Manager",
    org_unit_name: "Organization Unit Name",
    org_unit_parent: "Parent Organization Unit",
    org_stamp: "Organization Stamp",
    org_unit_stamp: "Organization Unit Stamp",
    org_units: "Org Units",
    orgunit_canSendOutboundAnnouncements:
      "The groups which the organization unit can send announcement to it",
    orgunit_canSendOutboundAnnouncements_flag: "Send announcement",
    orgunit_canSendOutboundDecisions:
      "The groups which the organization unit can send decision to it",
    orgunit_canSendOutboundDecisions_flag: "Send decision",
    outboundApprovalNormalUsers: "Outbound Approval Normal Users",
    outboundApprovalSecretUsers: "Outbound Approval Secret Users",
    outboundApprovalTopSecretUsers: "Outbound Approval Top Secret Users",
    outboundReviewerNormalUsers: "Outbound Reviewer Normal Users",
    outboundReviewerSecretUsers: "Outbound Reviewer Secret Users",
    outboundReviewerTopSecretUsers: "Outbound Reviewer Top Secret Users",
    outboundSenderNormalUsers: "Outbound Sender Normal Users",
    outboundSenderSecretUsers: "Outbound Sender Secret Users",
    outboundSenderTopSecretUsers: "Outbound Sender Top Secret Users",
    outbound_type: "Outbound Type",
    out_final_approver: "Outbound Final Approver",
    out_reply_ref_number: "Outbound Reply Reference Number",
    over_due: "OverDue",
    per_day: "Per Day",
    per_taskname: "Per Task Name",
    per_workflow: "Per Workflow",
    permited_org_unit_sent_to: "Permitted OrgUnit Sent To",
    permited_ext_entity_sent_to: "Permitted External Entity Sent To",
    phone: "Phone",
    previous_comment: "Previous Comment",
    param_grant_read_inbound_issuer:
      "Grant read access to inbound issuers group",
    param_inbound_fyi_route_option:
      "Send (FYI) Routing of Inbound Correspondence Method",
    picklist_ar_label: "Picklist Ar Label",
    picklist_en_label: "Picklist En Label",
    picklist_type: "Picklist Type",
    picklist_category: "Picklist Category",
    picklist_item: "Picklist Item",
    profile_name_ar: "Group Arabic Label",
    profile_name_en: "Group English Label",
    profile_code: "Group code",
    profile_views: "Group views",
    profile_users: "Group Users",
    quantity: "Quantity",
    reac_inbou_action: "React to Inbound Task - Default Action",
    reac_rej_inb_action: "React to rejected Inbound - Default Action",
    receive_acknowledge: "Receive Acknowledgment",
    receive_date_from: "Receive Date From",
    receive_date_to: "Receive Date To",
    reciever_type: "Reciever Type",
    receiving_entity: "Receiving Entity",
    recvinbNormalUsers: " Receive Normal Users",
    recvinbSecretUsers: "Receive Secret Users",
    recvinbTopSecretUsers: "Receive Top Secret Users",
    redirectting: "Redirecting ....",
    reject: "Reject",
    rejection_comment: "Rejection Comment",
    rejection_reason: "Rejection Reason",
    related_ref_num: "Related Correspondences",
    remarks: "Remarks",
    reminder: "Reminder Messages",
    reply_comment: "Reply Comment",
    reply_date: "Reply Date",
    report_name: "Report Name",
    reqired_action: "Required Action",
    resend: "Resend",
    review_correspondence: "Review Correspondence",
    route: "Route",
    route_comment: "Routing Comment",
    route_date: "Routing Date",
    route_date_from: "Routing Date (From)",
    route_date_to: "Routing Date (To)",
    route_from: "Routing From",
    route_from_org: "Routing From (Organization Unit)",
    route_from_user: "Routing From (User)",
    route_status: "Routing Status",
    route_sender_org: "Routing Sender (Organization Unit)",
    route_sender_user: "Routing Sender (User)",
    route_receiver_org: "Routing Receiver (Organization Unit)",
    route_receiver_user: "Routing Receiver (User)",
    route_to: "Route To",
    route_type: "Route Type",
    scan_user: "Scan User",
    search_contentSearch: "Search by Content",
    search_isDeleted: "Deleted",
    search_createdByMe: "Created By Me",
    security_level: "Security Level",
    select_approver: "Select Approver Organisation Unit",
    select_approver_user: "Select Approver User",
    select_reviewer_user: "Select Reviewer User",
    select_approval_user: "Select Approval User",
    select_issuers_users: "Issuers group",
    select_reviewer_users: "Reviewers group",
    select_approval_users: "Group Approvers",
    send_any_internal: "Restrict sending to specefic list of internal org unit",
    send_email_fyi_routing: "Send (FYI) Routing through e-mail",
    send_email_to_cc: "Sending email only to CC list",
    send_task_fyi_routing: "Send (FYI) Routing as a task",
    send_task_to_cc: "Sending task and its email to CC list",
    send_date: "Send Date",
    send_date_from: "Send Date From",
    send_date_to: "Send Date To",
    sender_id: "Sender ID",
    sender_name: "Sender Name",
    sender_phone: "Sender Phone",
    sender_type: "Sender Type",
    sending_method: "Sending Method",
    last_comment: "Previous Comment",
    sending_entity: "Sending Entity",
    task_sending_entity: "Task Sending Entity",

    sequence_number: "Sequence Number",
    scanIndexUsers: "Scan Index Users",
    short_number: "Short Number",
    show_orgunit: "Click here to show organizarion units",
    show_more: "Show More",
    show_less: "Show less",
    since: "Since",
    sign_date: "Sign Date",
    sign_date_from: "Sign Date From",
    sign_date_to: "Sign Date To",
    size: "Size",
    stamp_general: "General Stamp",
    stamp_review: "Reviewing Stamp",
    stamp_g2g: "G2G Stamp",
    stamp_type: "Stamp Type",
    stamp_of: "Stamp",
    start: "Start",
    start_task_date: "Start Task Date",
    status: "Status",
    subject: "Subject",
    task_analysis: "Task Analysis",
    task_name: "Task Name",
    task_sent_date: "Sent Date",
    tasks_completed: "Tasks Completed",
    task_due_date: "Task Due Date",
    template: "Template",
    template_name: "Template Name",
    template_file_name: "Template File Name",
    template_orgunit: "Template OrgUnits",
    time_unit: "Time Unit",
    to_user: "To User",
    total_num_tasks: "Total Tasks",
    true: "Yes",
    type: "Type",
    type_of_schema: "Type of Schema",
    type_of_segment: "Type of Segment",
    urgency_level: "Urgency Level",
    user: "User",
    user_en_name: "User English Name",
    user_ar_name: "User Arabic Name",
    user_civil_id: "Civil ID",
    user_two_factor_auth:
      "Enable Two Factor Authentication with login to system",
    user_title: "User Title",
    user_title_en_name: "User Title English Name",
    user_title_ar_name: "User Title Arabic Name",
    user_title_default: "Default",
    user_title_order: "Order",
    user_title_set: "In Corres.",
    user_login_name: "User Login Name",
    user_orgunit: "User Organization Unit",
    user_name: "User Name",
    user_pass: "Password",
    warning: "Warning!",
    welcome: "Welcome, ",
    yes: "Yes",
    org_unit_opentextInboundExternalFolderId:
      "opentext Inbound External Folder Id",
    org_unit_opentextInboundInternalFolderId:
      "opentext Inbound Internal Folder Id",
    org_unit_opentextOutboundExternalFolderId:
      "opentext Outbound External Folder Id",
    org_unit_opentextOutboundInternalFolderId:
      "opentext Outbound Internal Folder Id",
    org_unit_opentext: "OpenText",
    urgency_notification: "Urgency Levels",
    period_unit: "Notification Period",
    duration_unit: "Period Unit",
    escalation_after_how_many_reminders: "Escalation After How Many Reminders",
    corres_duration: "Correspondence Finish Duration",
    hour: "Hour",
    minute: "Minute",
    second: "Second",
    millisecond: "Milli Second",
    FYA: "FYA",
    FYI: "FYI",
    g2gCode: "G2G Site ID",
    g2gBranch: "G2G Branch ID",
    enableG2G: "Enable G2G",
    receiving_branch: "Sending Branch",
    size_file: "Max attachment file size (MB)",
    copy: "Copy to ",
    show_general: "General Show",
    users: "Users",
    read_receipt: "Read Receipt",
    sender_name_to: "Sender Name To",
    delegation_from: "Delegation From",
    delegation_to: "Delegation To",
    delegation_date_from: "Date From",
    delegation_date_to: "Date To",
    delegation_craeted_on: "Created On",
    delegation_status: "Status",
    delegations: "Delegations",
    delegation_days: "No. Of Days",
    content: "Content",
    my_delegation: "Delegation to me",
    delegation_history: "Delegation History",
    cc_user: "CC User",
    delegate: "Delegations : ",
    actiontype: "Action Type",
    domaintype: "Domain Type",
    actiondate: "Action Date",
    viewActions: "View Actions",
    orgUnitAbbreviation: "Org unit Abbreviation",
    display_alluser: "Display all users in the system",
    display_orgunit: "follow the organazation unit rules",
    user_pref_home_page: "Favorite home page",
    user_pref_inbox_view: "Favorite inbox page",
    user_pref_receiving_notifications: "Notifications you want to receive",
    user_pref_receiving_emails: "E-Mails you want to receive",
    user_pref_user_image: "Profile Image",
    user_pref_user_signautre: "Signautre",
    AllowedOrgUnit: "Allowed Org Unit",
    approve_orgunit: "Organizational unit of the group of approval",
  },
  "----------------- Buttons -----------------":
    "----------------- Buttons -----------------",
  btn: {
    login_with_hawyti: "Login with Hawyti",
    about: "About AlMersal",
    acquire: "Acquire",
    activate: "Activate",
    add_new: "Add New",
    add_segment: "Add Segment",
    adhoc_create: "Create Adhoc",
    advanced_search: "Advanced Search",
    announce_grp_assign_users: "Assign Users",
    attachment_edit: "Edit Attachment Data",
    auto_clearSelection: "Clear Selection",
    auto_search: "Search",
    auto_selectAll: "Select All",
    auto_showLess: "Show Less",
    auto_showMore: "Show More",
    back: "Back",
    browse: "Browse",
    cancel: "Cancel",
    change_profile_image: "Change Profile Image",
    change_signature_image: "Change Signature Image",
    create_continue: "Create & Continue",
    create_new: "Create & New",
    create_inbound: "Create Inbound",
    create_outbound: "Create Outbound",
    clear: "Clear",
    clear_options: "Reset Fields",
    close: "Close",
    back_page: "Back",
    complete: "Complete",
    complete_task_read: "Complete Task and Read Receipt",
    complete_task: "Complete Task",
    complete_tasks: "Complete Tasks",
    continue: "Continue",
    create: "Create",
    create_all: "Multi Create",
    create_schema: "Create Schema",
    change_file: "Change File",
    custom_duration: "Custom Duration",
    deactivate: "Deactivate",
    default: "Make Default",
    delete: "Delete",
    delete_draft: "Delete Draft",
    delete_schema: "Delete Schema",
    delete_segment: "Delete Segment",
    delivery_note_create: "Create Delivery Note",
    delivery_note_delete: "Delete Delivery Note",
    delivery_note_delete_create: "Delete & Create Delivery Note",
    download: "Download",
    downloadAll: "Download All",
    download_pdf: "Download as PDF",
    download_tiff: "Download as TIFF",
    download_template: "Download Template",
    edit: "Edit",
    edit_segment: "Edit Segment",
    finish: "Finish",
    filter: "Search Criteria",
    generate_barcode: "Generate Barcode",
    group: "Group",
    hidden: "Hidden",
    import: "Import",
    import_new_version: "Import New Version",
    inbound_save_ocr: "Save Text",
    corres_download_latest: "Download Latest Version",
    login: "Login",
    login_windows_auth: "Login by Windows Authentication",
    logout: "Logout",
    manual_admin: "Administrator Manual",
    manual_user: "User Manual",
    move: "Move",
    move_up: "Move Up",
    move_down: "Move Down",
    new_inbound: "New Inbound",
    new_outbound: "New Outbound",
    next: "Next",
    no: "No",
    ok: "Ok",
    previous: "Previous",
    print_barcode: "Print Barcode",
    refresh: "Refresh",
    report_view: "View Report",
    report_print: "Print Report",
    reset: "Reset",
    reset_barcode: "Reset Barcode",
    resubmit: "Resubmit",
    route_add: "Add Route",
    route_edit: "Edit Route",
    route_send: "Send Route",
    route_terminate: "Terminate Route",
    save: " Save",
    save_changes: "Save Changes",
    save_draft: "Save As Draft",
    save_schema: "Save Schema",
    scan: "Scan",
    search: "Search",
    seeAll: "See All",
    select: "Select",
    select_action: "Action",
    select_file: "Select File",
    sendG2G: "Send G2G",
    setting: "Settings",
    showmore: "Show more",
    start_print: "Start Print",
    stop: "Stop",
    submit: "Submit",
    switch_inbox_list: "Switch to List",
    switch_inbox_table: "Switch to Table",
    task_actions: "Action",
    task_other_actions: "Other Action",
    task_complete_edit: "Edit complete task data",
    task_remove: "Remove task from the complete list",
    task_sendDelayComment: "Send Task Delay Comment",
    tasks_complete_multi: "Complete Tasks",
    tasks_complete_multi_reply_routing: " Reply Routing Tasks",
    tasks_complete_multi_routings_replies:
      "Reply on Routing Tasks (Routing Replies)",
    tasks_complete_multi_finish_inbound: "Routing Replies and complete Inbound",
    title_set_corres: "Set in Corres.",
    title_delete_corres: "Remove from Corres.",
    title_change_order: "Change Order",
    title_reorder: "Reorder",
    title_swap_order: "Swap Order",
    today: "Today",
    upload: "Upload",
    upload_out_corres_doc: "Upload Outbound Correspondence Document",
    upload_files: "Upload Files",
    upload_template: "Upload Template",
    userPreference_addToOrgunit: "Add to Organization Unit",
    view: "View",
    yes: "Yes",
    assignUsersToProfile: "Assign users to group",
    show_views: "Click here to shows",
    show_users: "Click here to show users",
    assign: "Add",
    notread: "Make as unread",
    read: "Make as read",
    sync: "Sync Users",
    quickly_add_user: "Users Fast Add",
    permission: "Permissions",
    select_all: "Select All",
    replay_to: "Replay To",
    uploadNewVersion: "Upload New Version",
    viewHistory: "View History",
    create_close: "Create & Close",
    print_task_corr: "Print Task",
    downolad_templete: "Downolad Templete",
    user_preferences: "User Preferences",
    view_all: "View All",
    view_changes: "View Changes Only",
    SkipPdfConverter: "Skip Pdf Converter",
    loginwith: "Sign in with this user",
    send_user: "Send to user",
    quickly_add_orgunit: "Org unit Fast Add",
    delete_user: "Delete User",
    add_user: "Add user",
  },
  "----------------- Titles -----------------":
    "----------------- Titles -----------------",
  til: {
    performance: "Performance",
    about: "About AlMersal",
    add_attachment: "Add Attachment",
    add_cc: "Add CC",
    adhoc: "AdHoc",
    adhoc_create: "Create Adhoc",
    admin_group: "Delete Group",
    advancedSearchCirteria: "Advanced Search Cirteria",
    all: "All",
    announcement: "Announcement",
    announce_grp: "Announcment Group",
    announce_grp_assign_users: "Assign Users to Announcment Group",
    announce_grp_search: "Search for Announcment Group",
    app_notifications: "Application notifications",
    attachments: "Attachments",
    attachmentHistory: "Attachment History",
    attachment_create_multi_electronic: "Create electroinc attachments",
    attachment_uploading_list: "Uploading list",
    basic_info: "Basic Information",
    basicSearchCirteria: "Basic Search Cirteria",
    cc_orgunit: "CC Organization Unit",
    cc_user: "CC Users",
    contributor_group: "Edit Group",
    consumer_group: "Read Access Group",
    corr_filter: "Correspondence Filter",
    corr_out_created_me: "Created outbound correspondence",
    corr_out_reviewed_me: "Reviewed outbound correspondence",
    corr_out_approved_me: "Approved outbound correspondence",
    corr_in_created_me: "Created inbound correspondence",
    corr_in_routed_me: "Routed inbound correspondence",
    corr_in_routed_cc_me: "Routed inbound correspondence (CC)",
    corr_in_route_replied_me: "Replied routed inbound correspondence",
    corr_in_completed_me: "Completed inbound correspondence",
    corr_related: "Related Correspondences",
    delete_access_group: "Delete Access Group",
    default_actions: "Default Actions",
    details: "Details",
    edit: "Edit",
    edit_access_group: "Edit Access Group",
    electronic_attachment: "Electronic Attachment",
    external_inbound: "External Inbound",
    external_outbound: "External Outbound",
    ext_ent_search_criteria: "External Entity Search Criteria",
    fill_form: "Fill Form",
    filtertabs_all: "All",
    followup: "Follow Up",
    gen_corr_num_acquisition:
      " Generate Inbound Correspondence Number on Unit Acquisition",
    gen_corr_num_schema:
      " Generate Correspondence Sequence Number Based on Schema",
    gen_out_approval:
      "Generate Outbound/Internal Correspondence Number on Approval",
    gen_out_send_bas_approv: "Outbound Sender based on Final Approval",
    history: "History",
    import_ext_ent_template: "Import External Entities",
    inbound: "Inbound",
    inbound_edit_ocr_text: "Edit Correspondence Content Text",
    inbound_form: "Inbound Form",
    inbound_recipient_group: "Inbound Recipient Group",
    inbound_resubmit: "Resubmit Inbound",
    internal: "Internal",
    kpi: "My key performance indicator",
    login: "Login",
    medium_criteria: "Medium Criteria",
    more_info: "More Information",
    notification: "Notification",
    org_unit: "Organization Units",
    org_unit_code: "Org Unit Code",
    org_unit_data: "Organization Unit Data",
    org_unit_email: "Org Unit Email",
    org_unit_in_roles: "Organization Unit Inbound Roles",
    org_unit_name_ar: "Org Unit Arabic Name",
    org_unit_name_en: "Org Unit English Name",
    org_unit_out_roles: "Organization Unit Outbound Roles",
    org_unit_search_criteria: "Organization Unit Search Criteria",
    org_unit_users: "Organization Unit Users",
    orgunit_outbound_announcements_decisions: "Announcements and Decisions",
    outbound: "Outbound",
    outbound_file: "Outbound File",
    outbound_templates: "Outbound Templates",
    outbound_form: "Outbound Form",
    outbound_initiator_group: "Outbound Initiator Group",
    outbound_reviewer_group: "Outbound Reviewer Group",
    outbound_restrict_recipient: "Outbound Restrict Recipient",
    outbound_restrict_final_approval: "Outbound Restrict Final Approval",
    outbound_approval_group: "Outbound Approval Group",
    outbound_sender_group: "Outbound Sender Group",
    param_generate_corres_num_timing: "Generate Correspondence Number Timing",
    param_inbox: "Inbox",
    param_related_adhoc_workflow: "Values Related to Adhoc Workflow",
    param_related_inbound_workflow: "Values Related to Inbound Workflow",
    param_related_outbound_workflow: "Values Related to Outbound Workflow",
    param_webapp_setting: "Web Application Settings",
    picklist_filter: "Picklist Filter",
    picklist_items_list: "Picklist Items List",
    physical_attachment: "Physical Attachments",
    print_range_barcode: "Print Range Barcode",
    print_specific_barcode: "Print Specific Barcode",
    read_access_group: "Read Access Group",
    reset_barcode: "Reset Barcode",
    resubmit: "Resubmit",
    report_filter: "Report Filter",
    report_name: "Report Name",
    report_view: "Report View",
    route: "Route",
    routes: "Routes",
    routing_details: "Routing Details",
    route_orgunit: "Route Organization Units",
    route_user: "Route Users",
    save_reset: "Save & Reset",
    scan_index_group: "Scan Index Group",
    schema_items: "Schema Items",
    search: "Search",

    search_by_metadata: "Search by Meta-data",
    search_by_content: "Search by Corres. Content",
    search_corres: "Search Correspondences",
    search_criteria: "Search Criteria",
    search_ext_ent: "Search External Entity",
    search_result: "Search Result",
    search_org_unit: "Search Organization Unit",
    search_user: "Search User",
    segment: "Segment",
    settings: "Settings",
    stamps_list: "Orgunit Stamps List ",
    stamps_general_list: "General Stamps List",
    stamp_create: "Create Stamp",
    stamp_edit: "Edit Stamp",
    submit: "Submit",
    super_user_selection: "Super Admins Selection",
    taskSearchCirteria: "Task Search Criteria",
    task_sendDelayComment: "Send Task Delay Comment",
    tasks: "Tasks",
    task_details: "Task Details",
    tasks_complete_multi_reply_routing: "Reply on Routing Tasks",
    tasks_complete_multi_routings_replies:
      "Complete Reply on Routing Tasks (Routing Replies)",
    tasks_complete_multi_finish_inbound: "Routing Replies and complete Inbound",
    tasks_finishing_list: "Tasks List",
    template_list: "Template List",
    top_criteria: "Top Criteria",
    type_schema: "Type of Schema",
    upload_document: "Upload Doucment",
    user_filter: "User Filter",
    user_data: "User Data",
    user_preferences: "User Preferences",
    userPerferenceOrgunitsRolesSection: "User Roles in Organization Units",
    versions: "Versions",
    view: "View",
    warning: "Warning",
    P2B: "Correspondence Management System",
    profiles_list: "Groups List",
    profile_views: "Group Priviliges",
    assign_users_profile: "Assign Users Group",
    delivery: "Delivery Note",
    urgency_notification: "Manage Urgency Notifications",
    org_unit_G2G: "G2G",
    G2G_group: "Inbound Group",
    attachment_size: "Control maximum file size",
    externalApplications: "External Applications",
    ext_ent_search_delegation: "Delegation Search Criteria",
    choose_weekend_days: "Choose Weekend Days",
    official_vacations: "Official Vacations",
    add_official_vacations: "Add Official Vacations",

    AddComment: "Add Comment",
    comments: "Comments",
    orgunit_main: "Organizational units (targeted)",
    orgunit_sec: "Org units (directing and conforming copies)",
    table_view: "Table View",
    list_view: "List View",
  },
  "----------------- Tables -----------------":
    "----------------- Tables -----------------",
  tbl: {
    task_receiving_entity: "Task Receiving Entity",
    action: "Action",
    action_date: "Action Date",
    att_last_modifier: "Last modifier",
    att_last_modify_date: "Last modify date",
    basic: "Basic",
    creation_on: "Creation On",
    corr_date: "Corres. Date",
    corr_num: "Corres. Number",
    corr_type: "Corres. Type",
    corres_status: "Correspondence Status",
    correspondences: "Correspondences",
    currentPerformer: "Current Performer (User/Org. Unit)",
    date_created: "Date Created",
    description: "Description",
    document_name: "Document Name",
    document_type: "Document Type",
    DocumentOwner: "Owner Name",
    edit_date: "Edit Date",
    editor_name: "Editor Name",
    entries: "entries",
    fileSize: "File Size",
    fileType: "File Type",
    name: "Name",
    of: "of",
    order: "Order",
    performer_action: "performer Action",
    performer_comment: "performer Comment",
    performer_username: "performer Username",
    quantity: "Quantity",
    receiving_entity: "Receiving Entity",
    sending_entity: "Sending Entity",
    segment_type: "Segment Type Name",
    sent_date: "Sent Date",
    sender_name: "Sender Name",
    seq_num_length: "Sequence Number Length",
    show1to: "Showing 1 to",
    status: "Status",
    subject: "Subject",
    task: "Task",
    task_comment: "Task Comment",
    task_id: "Task ID",
    task_name: "Task Name",
    task_read_receipt: "Read Receipt",
    taskDueDate: "Task Due Date",
    type: "Type",
    value: "Value",
    notes: "Description",
    vacation_name: "Vacation Name",
    from_date: "Date From",
    to_date: "Date To",
  },
  "----------------- Messages -----------------":
    "----------------- Messages -----------------",
  msg: {
    task_submitted: "Task is successfully completetd",
    routes_sent: "Routes are successfully sent",
    sync_success: "successfully synchronized",
    del_success: "successfully deleted",
    create_success: "successfully created",
    if_del_holiday: "this holiday will be permently deleted ? ",
    save_working_hours: "working hours are successfully saved",
    delete_draft_corres: "the draft is successfully deleted",
    create_ex_success: "External Entity is created successfully",
    update_ex_success: "External Entity is updated successfully",
    adhoc_create: "Adhoc is created successfully",
    announce_grp_activate_q:
      "You will activate the seleted announcment group, if you click activate button",
    announce_grp_activated: "Announcment group is activated successfully",
    announce_grp_created: "Announcment group is created successfully",
    announce_grp_deactivate_q:
      "You will deactivate the seleted announcment group, if you click deactivate button",
    announce_grp_deactivated: "Announcment group is deactivated successfully",
    announce_grp_not_available: "No Announcment Groups Available",
    announce_grp_updated: "Announcment group is updated successfully",
    announce_grp_users_assigned: "Users are assigned successfully",
    are_you_sure: "Are You Sure?",
    attachment_failed: "Failed to Upload",
    attachment_not_start: "Not Start",
    attachment_success: "Uploaded",
    attachment_selected_files_errors:
      "The following files are not being added in uploading list ({{num}}):",
    attachment_uploaded_files_failed:
      "Some files were not being uploaded as attachments, Please click on upload files button again",
    attachment_uploaded_files_success:
      "The following files are being uploaded as attachments ({{num}}):",
    auto_complete_not_found: 'No states matching "{{value}}" were found',
    barcode_will_reset: "Barcode will be reseted",
    barcode_reseted: "Barcode is reseted successfully",
    cant_delete_corr: "cannot delete the correspondence",
    cannot_edit_corr_t: "You cannot edit the correspondence now",
    cannot_edit_corr_tc:
      "This correspondence is being sent, Please wait for a few minutes, then click the refresh button, If the correspondence was being sent after some time, Press edit and send the correspondence again.",
    cant_have_that_many: "You can't have that Many",
    code_exist: "This code already exist, use another code",
    corr_updated: "Correspondence is updated successfully",
    create_attachment: "Attachment Added successfully",
    click_to_hide: "click here to hide the list",
    click_to_see: "click here to see the list",
    default_task_comment: "Done",
    delete_attachment: "Attachment Deleted successfully",
    delegation_create_sucessfully: "Delegation Added successfully",
    "delegation_waring-message": "User already has delegation on same dates",
    delegation_terminate_sucessfully: "Delegation Deleted successfully",
    delegation_terminate: "You will delete the Delegation",
    delegation_cancel_message: "Delegation is successfully cancelled",
    delegation_cancel: "You will Cancel the Delegation",
    delegation_cancel_sucessfully: "Delegation Cancel successfully",
    delegation_cancel_start_days_message_warning:
      "Cannot Cancel delegation that its days starts",
    delegation_terminate_due_days_message_warning:
      "Cannot Terminate delegation that days not starts or days ends",
    delegation_mode: "You are now on delegation mode to user ",
    digital_signature_cancel_timeout:
      "Digital signture is canceled after passing 2 mintues without taking any action",
    digital_signature_cancel_user: "Digital signture is canceled by user",
    digital_signature_install:
      "Please install the digital signture application, then restart the PC, then complete the task again",
    digital_signature_method_not_exist:
      "There no method to digiatlly sign with the selected method",
    en_name_exist: "This english name already exist, use another value",
    ar_name_exist: "This arabic name already exist, use another value",
    download_modification:
      "Download template for modification ..then upload it again",
    errorPageOpen:
      "Something wrong happend when the page content is being loaded (link below), please try to open it again from the below link, and if the error happened again, please take a screenshot from the current screen and send it to support",
    error_task: "There is something wrong with task number:",
    ext_import_step1: "1-Download the external entities template",
    ext_import_step2: "2-Write the external entities inside the template",
    ext_import_step3: "3-Upload the external entities template",
    file_maxSize: "File size should not be more than",
    file_minSize: "File size should not be less than",
    file_pattern:
      "Unable to upload the file, This file type is not supported, The system is supporting: {{types}}",
    file_pattern_not:
      "File type is not supported, The system is supporting all types except: {{types}}",
    file_size50: "File type should be more than 50MB",
    file_maxWidth: "Image width should not be more than",
    file_maxHeight: "Image height should not be more than",
    file_type_docx: "File type is not supported only .docx type",
    file_name_maxSize:
      "File name length should not be more than following number",
    file_special_char: "File name should not contain the following characters",
    field_cannt0: "This field cannot equal 0 or start with 0",
    has_attachment: "Attachments Found",
    if_activate: "You will activate the selected organization unit(s)",
    if_activate_general: "You will activate the select(s)",
    if_deactivate: "You will deactivate the selected organization unit(s)",
    if_deactivate_general: "You will deactivate the select(s)",
    if_download: "If you download, You will download correspondence",
    if_download_general: "If you download, You will download Selected File",
    if_delete_draft_corres:
      "If you delete, you will delete this draft correspondence",
    if_delete_corres: "If you delete, you will this correspondence",
    if_delete_attachment:
      "If you select delete, You will delete the selected attachment",
    if_delete_all_attachment:
      "If you select delete, You will delete all attachments",
    if_delete_general:
      "You will delete the selected item(s) if you click delete button",
    if_delete_scaned:
      "You will delete the seleted page, if you click delete button",
    if_delete_all_scaned:
      "You will delete all pages, if you click delete button",
    if_discard: "If you choose yes, you will discard these changes",
    if_terminate_route:
      "If you choose terminate route, the route will be terminated",
    if_resubmit: "You will resubmit the correspondence",
    if_save:
      "if your select save we will save your routes and you can update it later through your routing tables",
    if_save_general: "You about to Save, choose cancel to not Save them",
    if_user_change_profile: "You About to change profile Picture",
    if_user_change_signature: "You About to change Signature",
    if_user_title_delete: "If you delete, You will delete the user title",
    if_user_title_cannot_delete:
      "You cannot delete the only title, or the default title",
    import_uploaded: "importing new version uploaded successfully",
    import_success: "Success imported rows",
    inbound_delete: "Inbound Correspondence is Deleted successfully",
    inbound_submitted: "Inbound Correspondence is submited successfully",
    inbound_saved: "Inbound Correspondence is saved successfully",
    inbox_no_finishInboundTasks: "There is no inbound tasks (Routings Replies)",
    inbox_no_replyOnRoutingTasks: "There is no reply on routing tasks",
    inbox_no_routingsRepliesTasks:
      "There is no reply on routing tasks (Routings Replies)",
    input_accept_englisLetterhNumberUnderScore:
      "This field accepts only the following 0-9 a-z A-Z underscore",
    invalid_login: "Invalid User name or password",
    invalid_user:
      "Invalid user access, Please contact with system administrator",
    maxlength: "This field max length {{length}} characters",
    maxlength4: "This field max length 4 characters ",
    maxlength9: "This field max length 9 characters ",
    maxlength16: "This field max length 16 characters ",
    maxlength25: "This field max length 25 characters ",
    maxlength32: "This field max length 32 characters ",
    maxlength64: "This field max length 64 characters ",
    maxlength128: "This field max length 128 characters ",
    maxlength255: "This field max length 255 characters ",
    maxlength512: "This field max length 512 characters ",
    maxlength500: "This field max length 500 characters ",
    minlength4: "This field min length 4 characters ",
    no_attachment: "No Attachments Available",
    no_commment_found: "No Comment Found",
    no_corres: "No Correspondence Found",
    no_data: "No Data Found",
    no_followup: "No Follow Up Found",
    no_history: "No History Found",
    no_notifications: "No Notifications Found",
    no_profiles: "No Groups Found",
    no_routes: "No Routes Found",
    no_searchResult: "No Result Found",
    no_statistics: "No Statistics Found",
    no_subject: "No Subject Found",
    no_tasks: "No Tasks Found",
    notify_Announcement:
      "Kindly be informed that user {{user_description}} has sent an announcement, the announcement details as follows:",
    notify_CCUser:
      "Kindly be informed that a CC received for your information only, the correspondence details as follows:",
    notify_clickHere: "To view this correspondence please click Here",
    notify_Decision:
      "Kindly be informed that user {{user_description}} has sent a decision, the decision details as follows:",
    notify_Delegation:
      "Kindly be informed that you have been delegated on behalf of user {{user_description}} for the period between {{start_date}} and {{end_date}}",
    notify_IssuerFinalAprroval:
      "Kindly be informed that user {{user_description}} has finally approved the following correspondence that you have issued:",
    notify_period: "You must enter number from 1 to 365",
    notify_ReadReceipt:
      "Kindly be informed that the {{task_name}} Task has been read by {{user_description}} for the following correspondence:",
    notify_RejectInternalToApproval:
      "Kindly be informed that user {{user_description}} has rejected the following correspondence that you have finally approved:",
    notify_RouteCC:
      "Kindly be informed that a CC received for your information only, the correspondence details as follows:",
    notify_RouteFyi:
      "Kindly be informed that a new correspondence received for your information only, the correspondence details as follows:",
    notify_SendAdHoc:
      "Kindly be informed that the {{task_name}} task is sent to you by {{user_description}}, Kindly take an action on the task, the correspondence details as follows:",
    notify_TaskAcquire:
      "Kindly be informed that the {{task_name}} task has been acquired by {{user_description}} for the following correspondence:",
    notify_TaskDelayComment:
      "Kindly be informed that the reply on {{task_name}} task will be delayed by {{user_description}} for the following correspondence:",
    orgunit_deactivate: "OrgUnit Deactivated successfully",
    orgunit_activate: "OrgUnit Activated successfully",
    orgunit_create: "OrgUnit Created successfully",
    orgunit_outbound_save: "OrgUnit Outbound Users Saved successfully",
    orgunit_inbound_save: "OrgUnit inbound Users Saved successfully",
    orgunit_updated: "OrgUnit Updated successfully",
    orgunit_users_save: "OrgUnit Users Saved successfully",
    outbound_delete: "Outbound Correspondence is Deleted successfully",
    outbound_submitted: "Outbound Correspondence is submited successfully",
    outbound_saved: "Outbound Correspondence is saved successfully",
    outbound_template_download:
      "Template is Downloaded successfully, Please upload updated version",
    outbound_template_upload: "Template is Uploaded successfully",
    outbound_template_create: "Template Created successfully",
    outbound_template_update: "Template Updated successfully",
    outbound_template_delete: "Template Deleted successfully",
    pls_select: "Please Select Area to Crop",
    pls_add_files: "No files exist, please add files",
    start_digital_signature_process:
      "The corrosponedence document is sent to you in your mobile to sign it digitally, Please sign it within 2 mintues",
    q_do_want_continue_digital_signature_process:
      "It has been two minutes since You started the digital signature, Do want continue the digital signature process?",
    q_do_want_save_default_inbox_list:
      "Do you want to make the inbox as list view the default view?",
    q_do_want_save_default_inbox_table:
      "Do you want to make the inbox as table view the default view?",
    report_generated: "Report is generate successfully",
    report_no_users_available: "No users in this organization unit",
    required: "This field required",
    requiredWithoutSpecial:
      "This field required, You can enter (English Letters and Numbers, Arabic Letters and Numbers, Space, -, _, .)",
    route_added: "Routes are added successfully",
    route_to: "Route to ",
    route_before: " is routed before",
    routed_before: "Routed before",
    routed_not_before: "Not routed before",
    routes_routed_before:
      "Some of added routes were sent before by other user, press Send Route button to send.",
    route_delete: "Route is deleted successfully",
    route_update: "Route is updated successfully",
    route_terminated: "Route is terminated successfully",
    save_route: "Would you like to save your route ?",
    segment_type_added_before: "This segment type is added before",
    select_orgunit:
      "Select organization unit from the tree to get the correspondences",
    select_new_period: "Select a new period to get the statistics",
    short_number_exist: "This short number already exist, use another value",
    select_user: "Select User",
    select_picklist_type: "Kindly Select Picklist Type",
    session_timeout_login:
      "The session time is finished, Please login again to renew the period, or Logout",
    session_timeout_sso:
      "The session time is finished, Please wait a few moments",
    some_external_exist_short:
      "There are some external entity contains this short number",
    some_external_exist_en:
      "There are some external entity contains this english name,",
    some_external_exist_ar:
      "There are some external entity contains this arabic name,",
    something_wrong_happened:
      "Some wrong happened when getting some data, Please try again",
    stamp_orgunit_duplicated:
      "The selected organization unit already had a stamp, Please select another organization unit.",
    stamp_if_delete:
      "If you choose delete, you will delete the organization unit stamp",
    stamp_create: "The organization unit stamp is created successfully",
    stamp_edit: "The organization unit stamp is updated successfully",
    stamp_delete: "The organization unit stamp is deleted successfully",
    stamp_save_settings: "The settings are saved",
    task_already_completed: "This task is completed before",
    task_completed: "Task is completed successfully",
    tasks_completed: "Tasks are completed successfully",
    tasks_multi_finished_failed:
      "Failed on finishing some tasks, please try again, and if the same problem happened again, send the task number to support.",
    task_finish_q: "If you choose finish, the task will be finished",
    task_overdue: "Overdue Task",
    task_previous_comment: "Previous user comment :",
    task_complete_not_start: "Not Start",
    task_complete_success: "Complete task success",
    task_complete_failed: "Complete task failed",
    task_delay_comment_sent: "Task delay comment is sent successfully",
    today_future: "This field value must be todat or in future",
    the_corr: " the Correspondence",
    twoFactorAuthenticationWaiting:
      "Kindly accept the two factor authentication from thhe mobile app",
    unauthorized: "You don't have permission to enter this page",
    unauthorized_home_page1:
      "Please change the favorite home page from user preferences",
    unauthorized_home_page2: "For going to user preferences page Click Here",
    unauthorized_home_page3:
      "Or click on your page profile, then select user preferences from the dropdown.",
    update_attachment: "Attachment Updated successfully",
    upload_first:
      "Upload the correspondence first to unlock the meta data area",
    upload_first_attachment:
      "Upload the correspondence first to unlock the attachment area",
    users_save: "Org-unit users is saved successfully",
    user_data_save: "User data is saved successfully",
    userPreference_noOrgUnitData: "This user is not added to any role",
    userPreference_orgunitDuplicate:
      "This organization unit ({{data}}) is added before, you can cancel the addtion and select it from dropdown",
    userPerference_role_add: "This user is added to the organiztion unit",
    userPerference_role_save: "Roles are saved successfully",
    super_admin_save: "Super admin data is saved successfully",
    wrong_email_format: "Wrong email format",
    wrong_phone_format: "Wrong phone format, use 0-9 + - . space",
    wrong_fax_format: "Wrong fax format, use 0-9 + space",
    you_not_assign: "You are not assigned in any organization unit",
    you_not_assign_inbound: "You are not assigned in any organization unit",
    you_should_select: "you should select at least one draft",
    you_will: "You Will ",
    parameter_save: "Application Parameters is Saved successfully",
    outbound_task_confirem_title:
      "Confirm Message for sending this correspondence through post office",
    outbound_task_confirem_contant:
      "so.. You should print this correspondence now .",
    outbound_task_confirm_contant:
      "You will send this correspondence through post office, Please print the correspondence, and check the checkbox",
    hint_keywords: "Press Enter key to add new keyword",
    error_title: "Error",
    error_message: "Please contact system administrator",
    add_picklist: "Picklist Item is added successfully",
    edit_picklist: "Picklist Item is updated successfully",
    pickList_activate: "Picklist Item is activated successfully",
    pickList_deactivate: "Picklist Item is deactivated successfully",
    pickList_delete: "Picklist Item is deleted successfully",
    pickList_used_delete:
      "Picklist Item cannot be deleted because It is used in some correspondences",
    correspondence_add: "Correspondence Schema is Added successfully",
    correspondence_save: "Correspondence Schema is Saved successfully",
    correspondence_deleted: "Correspondence is deleted successfully",
    corres_deleted: "Correspondence Schema is Deleted successfully",
    fill_require_data: "Please fill the required data",
    app_profile_delete: "Group is Deleted successfully",
    app_profile_create: "Group is Added successfully",
    app_profile_update: "Group is Updated successfully",
    app_profile_users_assigned: "Users is Assigned successfully",
    send_message_succ: "Message sent successfully",
    create_delivery: "Delivery Note Added successfully",
    delivery_note_delete_q:
      "If you select delete, You will delete the delivery note",
    delivery_note_delete_add_q:
      "If you select delete, You will delete the old delivery note and add a new one",
    delivery_note_deleted: "Delivery Note Deleted successfully",
    delivery_note_not_available: "No delivery note is added",
    if_Sync_users: "Do you need to sync the users from your system ?",
    you_not_assign_delivery: "You are not assigned in Add delivery Note",
    no_action: "No Action",
    outbound_task_hasphysical: "Please note there is physical attachments",
    outbound_task_enable_g2g:
      "This external entity is not registered as G2G entity",
    outbound_task_hasElectronic: "Are you Send Electronic Attachments",
    outbound_task_hasElectronicwarning:
      "The G2G supports attachments of type PDF and Tiff only",
    you_not_assign_delete_delivery:
      "You are not assigned in Delete delivery Note",
    attachment_size_error: "File size should be from 1 to 200 MB",
    outbound_task_reload: "Please Reload The Task Again",
    task_unauthorized_completed: "This Task is unauthorized To You",
    task_task_taked: "This task has been accepted by someone",
    hint_readReceipt:
      "Receive an email when the task is read by the task recipient",
    orgunit_quickly_create: "Users successfully added to organizational unit",
    inlinepassword_mode: "You are now logged in as a user",
    save_weekly_holiday_error: "Error saving weekends",
    save_annual_holiday_error: "Error in keeping official holidays",
    save_annual_holiday: "The holiday was saved successfully",
    update_annual_holiday: "The holiday was updated successfully",
    delete_annual_holiday: "The holiday was deleted successfully",
    delete_annual_holiday_error: "Error deleting holiday",
    if_delete_annual_holiday: "Do you want to delete this holiday?",
    save_correspondance_note: "The Comment was saved successfully",
    no_notes: "No Notes Found",
    delete_urgancy_notification: "Urgancy Notification is Deleted successfully",
    update_urgancy_notification: "Urgancy Notification is Updated successfully",
    add_urgancy_notification: "Urgancy Notification is Added successfully",
    delegation_update_sucessfully: "Delegation is updated successfully",
    work_done: "Done Work",
    login_again: "Please login again",
  },
  "----------------- Main Menu -----------------":
    "----------------- Main Menu -----------------",
  mnu: {
    create_delegation: "Create Delegation",
    view_delegation: "view delegation",
    translation_manager: "Translation Manager",
    sla: "sla",
    task_management: "Task Management",
    accessibility_priviliges: "Application Priviliges",
    announcements_groups: "Announcements Groups",
    app_parameters: "App. Paramaters",
    barcode: "Barcode",
    corres_schema: "Corres. Schema",
    dashboard: "Dashboard",
    external_entity: "External Entity",
    inbox: "Inbox",
    inbox_g2g: "G2G Inbound",
    inbound: "Create Inbound",
    g2g_task: "G2G Task",
    organization_unit: "Organization Unit",
    outbound: "Create Outbound",
    outbound_templates: "Outbound Templates",
    picklists: "Picklists",
    reports: "Reports",
    users_preferences: "Users Preferences",
    delegation: "Delegation",
    auditing: "Auditing",
    calendar: "Calendar",
    search: "Search for Correspondences",
    created_by_me: "Created By Me",
    super_user_management: "Super Admins Management",
    stamps: "Stamps",
    urgency_notification: "Urgency Notification",
  },
  "----------------- Page Header -----------------":
    "----------------- Page Header -----------------",
  ph: {
    accessibility_priviliges: "Application Priviliges",
    announcements_groups: "Announcements Groups",
    app_parameters: "App. Paramaters",
    app_notifications: "Application Notifications",
    barcode: "Barcode",
    corres_schema: "Correspondence Schema Number",
    dashboard: "Dashboard",
    external_entity: "External Entity",
    inbox: "Inbox",
    inbox_g2g: "G2G Inbound",
    inbound: "Inbound",
    g2g_task: "G2G Task",
    organization_unit: "Organization Unit",
    outbound: "Outbound",
    outbound_templates: "Outbound Templates",
    picklists: "Picklists",
    reports: "Reports",
    users_preferences: "Users Preferences",
    delegation: "Delegation",
    auditing: "Auditing",
    calendar: "Calendar",
    search: "Search for Correspondences",
    created_by_me: "Created By Me",
    super_user_management: "Super Admins Management",
    stamps: "Stamps",
    urgency_notification: "Urgency Notification",
  },
  "----------------- Picklist -----------------":
    "----------------- Picklist -----------------",
  pk: {
    announcment_group: "Announcement Group",
    approval_subtype: "Approval SubType",
    correspondence_type: "Correspondence Type",
    document_type: "Document Type",
    escalation_performer: "Escalation Performer",
    external_entity_classification: "External Entity Classification",
    external_entity_sending_method: "External Entity Sending Method",
    history_status: "History Status",
    inbound_source: "Inbound Source",
    language: "Language",
    org_unit_level: "OrgUnit Level",
    outbound_sending_type: "Outbound Sending Type",
    outbound_types: "Outbound Types",
    physical_attachment_type: "Physical Attachment Type",
    rejection_folder: "Rejection Folder",
    rejection_reason: "Rejection Reason",
    required_action: "Required Action",
    reviewer_actions: "Reviewer Actions",
    security_level: "Security Level",
    sender_action: "Sender Action",
    sender_reject_outbound: "Sender Reject Outbound",
    stamp_options: "Stamp Options",
    status: "Status",
    task_subject: "Task Subject",
    urgency_level: "Urgency Level",

    segment_Inbound: "External Inbound",
    segment_Outbound: "External Outbound",
    segment_Internal: "Internal Correspondences",
    segment_InternalAnnouncement: "Internal Correspondences (Announcement)",
    segment_InternalDecision: "Internal Correspondences (Decision)",
    segment_InternalMeeting: "Internal Correspondences (Meeting)",
  },

  "----------------- ToolTip -----------------":
    "----------------- ToolTip -----------------",
  ttp_search: "Search",

  "----------------- Dynamic -----------------":
    "----------------- Dynamic -----------------",
  adhoc: "Adhoc",
  Adhoc: "Adhoc",
  all: "All",
  All: "All",
  Announcement: "Announcement",
  "Application Paramters Management": "Application Paramters Management",
  "Approve Outbound": "Approve Outbound",
  archived: "Archived",
  Browse: "Browse",
  "Change file": "Change File",
  "Create Inbound": "Create Inbound",
  "Create Outbound": "Create Outbound",
  Custom: "Custom",
  dashboard: "Dashboard",
  Draft: "Draft",
  "Edit Draft Outbound": "Edit Draft Outbound",
  "Edit Inbound": "Edit Inbound",
  "External Entity": "External Entity",
  From: "From",
  generic: "Generic",
  global_language_en: "English",
  global_language_ar: "Arabic",
  "Hide Advanced Search": "Hide Advanced Search",
  Hybrid: "Hybrid",
  inbound: "Inbound",
  Inbound: "External Inbound",
  inbox: "Inbox",
  "Incoming External": "External Inbound",
  Internal: "Internal Correspondences",
  isDueDate: "Overdue",
  "New Inbound": "New Inbound",
  "Organization Unit": "Organization Unit",
  "Organization Unit - View": "Organization Unit View",
  "Organization Unit Form": "Organization Unit Form",
  "Org Unit Manager": "Org Unit Manager",
  outbound: "Outbound",
  Outbound: "External Outbound",
  "Outgoing External": "External Outbound",
  overdue: "Overdue",
  "Parent Organization Unit": "Parent Organization Unit",
  "Rejected Inbound": "Rejected Inbound",
  "Rejected Outbound": "Rejected Outbound",
  "Rejected Routing": "Rejected Routing",
  "Reply Adhoc": "Reply Adhoc",
  "Reply Routing": "Reply Routing",
  "Review Outbound": "Review Outbound",
  "Routing Replies": "Routing Replies",
  Search: "Search",
  "Send For Approval": "Send For Approval",
  "Send For Review": "Send For Review",
  "Send Outbound": "Send Outbound",
  "Show Advanced Search": "Show Advanced Search",
  Submit: "Submit",
  System: "System",
  task_name: "Task Name",
  To: "TO",
  Today: "Today",
  "This Month": "This Month",
  "This Week": "This Week",
  "View Routing": "View Routing",
  User: "User",
  Month: "Month",
  Day: "Day",
  Hour: "Hour",
  "Send For Approval skip Review": "Skip Review and Send For Approval",

  Saturday: "Saturday",
  Sunday: "Sunday",
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",

  notification_desc: "enDesc",
  Desc: "DescEn",
  external_enitity_desc: "descEn",
  general_enitity_desc: "descEn",
  org_unit_desc: "orgUnitDescEn",
  org_unit_desc2: "orgUnitEnglishDesc",
  ext_entity_desc: "extEntityDescEn",
  announcement_desc: "name",
  picklist_label: "picklistEnLabel",
  route_description: "enDescription",
  routeFromOrganizationUnit: "routeFromOrganizationUnitEn",
  routeToOrganizationUnit: "routeToOrganizationUnitEn",
  dd_userTitle: "enUserTitle",
  user_title_ae: "englishTitle",
  corrStatusPickListDescription: "corrStatusPickListEnDescription",
  corrTypePickListDescription: "corrTypePickListEnDescription",
  sendingEntityDescription: "sendingEntityEnDescription",
  task_action_description: "taskActionEnName",
  receivingEntityDescription: "receivingEntityEnDescription",
  user_description: "enDescription",
  orgunit_allowedCode: "enName",
};
